### ISSUE TITLE
Blockwise comments broken with context-commentstring

### ISSUE THREAD

**Issue by sQVe** [numToStr/Comment.nvim#10]
👋🏼,

Cheers for making a great commenting plugin!

I'm running the following config:
```lua
require('Comment').setup({
    ignore = '^$',
    pre_hook = function()
        return
            require('ts_context_commentstring.internal').calculate_commentstring()
    end
})
```

Take the following *TypeScript* snippet:
```typescript
if (text == null) {
  text = await readTextFromStdin();
}
```

Running `gbc` on the `if` line gives me:
```typescript
// if (text == null) {

```
when it really should give me:
```typescript
/* if (text == null) { */

```

**Comment by numToStr** [comment]
The problem might be if context-commenstring returning a linewise commentstring while running `gbc` and as you already know `pre_hook` overrides the commentstring.

Someone was also facing this dilemma https://www.reddit.com/r/neovim/comments/q35328/comment/hfstsld/?utm_source=share&utm_medium=web2x&context=3

**Comment by sQVe** [comment]
This is an example:


https://user-images.githubusercontent.com/2284724/136540386-bfd21594-89d2-4c6f-9b40-24168e464186.mp4

**Comment by numToStr** [comment]
Yeah, I figured that much. As we know block comments should have both LHS and RHS part in the comments. But line comments only have RHS.

```lua
-- Javascript block comments
--  {*               %s                *}
--  |                 |                 |
-- lhs           placeholder           rhs

-- Javascript line comments
--  //               %s
--  |                 |
-- lhs           placeholder
```

And to be honest, IDK how to resolve this situation but I am planning to update the `pre_hook` method to give you the comment type ie. line/block, and mode ie. toggle/comment/uncomment as the arguments. I still don't know after this whether anyone we'll be able to fully resolve this or not.

**Comment by sQVe** [comment]
That would be an improvement but would obviously disable the proper comment string when doing block commenting. `gb` would still not work for JSX.

**Comment by numToStr** [comment]
It's challenging to make both plugins sing together 😆

**Comment by numToStr** [comment]
@JoosepAlviste Surely, that should fix this. As the `pre_hook` is now aware of the type of the comment so anyone can do this.

```lua
{
    pre_hook = function(ctx)
        local U = require('Comment.utils')
        local ty = ctx.ctype == U.ctype.line and 'single' or 'multi'
        return require('ts_context_commentstring.internal').calculate_commentstring(ty)
    end,
}
```

**Comment by sQVe** [comment]
I just tested this some more and it's working quite nicely but it does have some quirks. It seems like the `commentstring` is evaluated on the line where the *cursor* is. 

Given this code:

```jsx
<button
  type="button"
  onClick={() => {
    actions.copyStringsToClipboard();
  }}
>
```

If I select everything from `<button` to `}}` I would assume that it would set the `commentstring` to `{/*` and not `//`. Only when I select down to `>` it uses the correct `{/*`.

**Comment by xeluxee** [comment]
@sQVe @numToStr I think I've found a solution to this problem using internal `ts-context-commentstring` functions:

``` lua
pre_hook = function(ctx)
  local tsccu = require('ts_context_commentstring.utils')
  local tscci = require('ts_context_commentstring.internal')
  local node, language_tree = tsccu.get_node_at_cursor_start_of_line(
    vim.tbl_keys(tscci.config)
  )

  if not node and not language_tree then
    return nil
  end

  local language = language_tree:lang()
  local language_config = require("Comment.ft").get(language, ctx.ctype)

  return tscci.check_node(node, language_config)
end

```

The above code is partially copied by `calculate_commentstring` function from `ts-context-commentstring`

**Comment by JoosepAlviste** [comment]
Hey! I added a configuration option to `nvim-ts-context-commentstring` that would allow to do this: https://github.com/JoosepAlviste/nvim-ts-context-commentstring/pull/26

The way to use it with `Comment.nvim` would be like so:

```lua
require('Comment').setup {
  pre_hook = function(ctx)
    local U = require 'Comment.utils'
    local type = ctx.ctype == U.ctype.line and '__default' or '__multiline'
    return require('ts_context_commentstring.internal').calculate_commentstring {
      key = type,
    }
  end,
}
```

Please take a look at the branch and let me know if it works for your use-case!

PS: I'm also planning to add a way to customize the location where the treesitter tree traversal is started (currently only on the first non-blank char on the cursor's line). This would make it possible to comment something like this in JSX when running `gciW`:

```tsx
<View /* style={styles.filterDropdownsContainer} */ />
```

CC @sQVe @numToStr

**Comment by sQVe** [comment]
@JoosepAlviste That works perfectly for my use-case in `jsx`! 🎉

**Comment by numToStr** [comment]
@JoosepAlviste That's wonderful, thanks. I personally don't use `nvim-ts-context-commentstring` but it seems to fix the issue as @sQVe said.

---

@sQVe Feel free to close the issue.
