### ISSUE TITLE
Allow default line commenting to /* */ for C

### ISSUE THREAD

**Issue by mortezadadgar** [numToStr/Comment.nvim#100]
Hey,
currently line commenting(gcc) comments line starting with // and /* */ for block commenting, I like to have /* */ commenting for one line comments as well, it's also the default behavior with tpope's commentary plugin.

**Comment by numToStr** [comment]
You can achieve the same. You just need to configure it using `pre_hook`.

```lua
local U = require('Comment.utils')
local F = require('Comment.ft')

require('Comment').setup({
    pre_hook = function()
        local filetype = vim.bo.filetype
        -- Always return blockwise commentstring for `c`
        if filetype == 'c' then
            return F.get(filetype, U.ctype.block)
        end
    end,
})
```
