### ISSUE TITLE
Smart `gc{motion}`

### ISSUE THREAD

**Issue by kuntau** [numToStr/Comment.nvim#103]
Hi, I'm no sure to call this bug or not, but coming from `tcomment` I miss this feature the most.

Let's say I have the following situation
```lua
local str = 'This is a test'
-- local str = 'This is not a test'
```
with `tcomment` I can do `gc{motion}` let's say `j` or `k` and the line will switch comment and become
```lua
-- local str = 'This is a test'
local str = 'This is not a test'
```
with `Comment.nvim` resulting code is
```lua
-- local str = 'This is a test'
-- -- local str = 'This is not a test'
```
so to get the result like `tcomment` I have to press `gcc` twice, one on each line.
It's not much but I think this behavior is quality of life improvement.

Thank you for this amazing plugin 👍🏽

**Comment by xeluxee** [comment]
We've already discussed this feature in #17

Since many users would benefit from this feature I think it should be included in extra (or experimental) mappings

**Comment by numToStr** [comment]
Closing in favour of #17
