### ISSUE TITLE
[Feature request] Configure operator pending mode and visual mode mappings separately

### ISSUE THREAD

**Issue by jebaum** [numToStr/Comment.nvim#104]
Currently, `opleader.line` and `opleader.block` are used to configure both operator pending mode mappings and visual mode mappings. I think it would be a bit nicer to have separate config options for the two (that is, add another couple of options for `visual.line` and `visual.block`).

My personal use case for this is that I pretty much never use operator pending mode, but use normal mode, count prefixes and visual mode all the time. The way mappings are configured currently, you can't have the same key for toggling comments in both normal and visual mode (without disabling all mappings and creating them yourself, which is what I currently do).

Happy to submit a PR for this if you'd accept it, but I expect it would be a ~2 minute change and the main complication would be making the config somewhat backward incompatible, so not sure how you'd want to handle it.

On a somewhat related note, I think the implementation of the mappings themselves could be simplified, and `toggle_current_linewise_op` could be made redundant if `toggle_linewise_count` used `v:count1` instead of `v:count`. Then it would still work to toggle a single line when the user doesn't type a count prefix. Haven't tried it so might be missing something.

**Comment by numToStr** [comment]
> My personal use case for this is that I pretty much never use operator pending mode, but use normal mode, count prefixes and visual mode all the time. The way mappings are configured currently, you can't have the same key for toggling comments in both normal and visual mode (without disabling all mappings and creating them yourself, which is what I currently do).
> 
> Happy to submit a PR for this if you'd accept it, but I expect it would be a ~2 minute change and the main complication would be making the config somewhat backward incompatible, so not sure how you'd want to handle it.

I can totally understand but the mappings are a very tough nut to crack. Everyone has their preference for mappings but personally, I aimed for the sanest approach by following vim's approach like `di{` and `Vd` is relatively similar to `gci{` and `Vgc`.


> On a somewhat related note, I think the implementation of the mappings themselves could be simplified, and `toggle_current_linewise_op` could be made redundant if `toggle_linewise_count` used `v:count1` instead of `v:count`. 

`toggle_current_linewise_op` is dot-repeatable whereas `toggle_linewise_count` is not.

**Comment by jebaum** [comment]
That all makes sense, you've obviously thought about this a lot more deeply than I have. I can get the behavior I want by manually setting the mappings so I think nothing should change here. Thanks for the detailed answer!

**Comment by numToStr** [comment]
FYI: With #98 you can more easily setup your own custom keybindings.
