### ISSUE TITLE
Is it possible to configure Commment.nvim to add a new comment on a new line

### ISSUE THREAD

**Issue by benwoodward** [numToStr/Comment.nvim#105]
Assuming I have the following:

```javascript
// one
// two
// three
foo
bar
```

and my cursor is on 'three', then I would like to be able to press `o` and for every new line created in insert mode below this one to be automatically-commented. If, however, I want to add an uncommented line after `// three` then I just move to `foo` and press `O` to create an uncommented new line in insert mode _above_ `foo`. This is commenting behaviour that I'm used to, and it's a lot less work than pressing `gco` > type comment `esc``gco` > type comment `esc``gco` > type comment. 

Is this currently possible in `Comment.nvim`?

**Comment by numToStr** [comment]
≥ then I would like to be able to press o and for every new line created in insert mode below this one to be automatically-commented. If, however, I want to add an uncommented line after // three then I just move to foo and press O to create an uncommented new line in insert mode above foo.

This is vim native behaviour. I don't understand what do you exactly want?

**Comment by benwoodward** [comment]
Oh didn't realise it was native behaviour. For some reason this behaviour doesn't occur for me. Assumed it was due to Comment.nvim. I need to figure out what's causing this. Perhaps it's a vim option. I'll update once I've done some more investigation.
