### ISSUE TITLE
Paste as comment

### ISSUE THREAD

**Issue by dataO1** [numToStr/Comment.nvim#106]
I often find my self wanting to paste yanked text as a comment.

Example:
`This is an exam|ple text` -> `This is an example text #|with a comment`

Would this somehow be possible to implement in this plugin? I think what i want is some sort of pasting motion, but i couldn't find anything like that on the internet.
I'm happy for any pointers and tips.

**Comment by gegoune** [comment]
You can use `gcA` mapping (might be in extras, double check in docs.

**Comment by numToStr** [comment]
As @gegoune pointed out, `gcA` mapping will add the comment at the end of line and leaves you in the insert mode. From there you can paste your yanked text.

**Comment by dataO1** [comment]
I know about gcA, but i was wondering if it would be possible with a single command without entering insert mode and having to manually paste the register with Ctrl-Shift v. Something like `pcA` (paste as comment at end of line).

I know this could be done with a key map, but i was also wondering if such a paste motion/action exists in vim or as a plugin.

**Comment by numToStr** [comment]
@dataO1 You can do that with the following mapping
```vim
map <leader>pc gcA<ESC>p
```
But If your yanked text contains line feed ie. `\n` then it will paste below the current line.

---

I am going to close this issue now. As this is out of scope for the plugin :)
