### ISSUE TITLE
Support compound (dot-separated) filetypes i.e `ansible.yaml`, `ios.swift`

### ISSUE THREAD

**Issue by jandamm** [numToStr/Comment.nvim#111]
Hey,

I'm using my custom filetype (`ios.swift`).
I'd expect that it'd be matched against `ios` (which hasn't a rule) and then uses the `swift` format.

Are you interested in supporting this "feature" or should I just add this specific filetype myself?

**Comment by numToStr** [comment]
I don't intend to add custom filetypes unless the filetype is supported by vim or some famous filetype plugins.

**Comment by numToStr** [comment]
You can just use `vim.filetype.add` to add custom filetype (I hope you already knew that 😄)

---

I am going to close this as this is out of scope for the plugin.

**Comment by jandamm** [comment]
Well this filetype is supported by vim since vim splits filetypes by `.` and then applies the filetypes in reverse order.
So `subtype.shell` would first apply `shell` and then `subtype`.

In the context of this plugin it would mean that you'd split the filetype by `.` and then use the first matching filetype - instead of just comparing the filetype.

**Comment by numToStr** [comment]
I don't think I wanted to add that much code just for a single filetype.

**Comment by numToStr** [comment]
What's the filetype that's get attached to the file?

**Comment by jandamm** [comment]
It's not a single filetype. It's vims default filetype pattern matching.
Try `:set ft=some.lua` in a lua buffer. You'll see that it still applies lua. And would then also apply `ftplugin/some.lua`.

See also:
https://stackoverflow.com/questions/2601403/multiple-file-types-in-vim

**Comment by numToStr** [comment]
By that means `ios.swift` applies `ios` as a filetype?

**Comment by jandamm** [comment]
Yes it applies the filetype `swift` and then applies the filetype `ios`.
So in this example tree-sitter/lsp uses `swift` and I can then use `ios` to further refine what happens.

**Comment by numToStr** [comment]
Can you give me a sample file?

**Comment by jandamm** [comment]
Put the following files in your runtime:

ftdetect/some.vim
```vim
autocmd Filetype lua set ft=some.lua
```

ftplugin/some.vim
```
set commentstring=hi%s
```

When you now open any lua file your filetype will be `some.lua`.
Everything will be as if the filetype is `lua` except the commentstring is overwritten with `hi%s`.

**Comment by numToStr** [comment]
> Put the following files in your runtime:
> 
> ftdetect/some.vim
> 
> ```viml
> autocmd Filetype lua set ft=some.lua
> ```
> 
> ftplugin/some.vim

It seems, doing this broke treesitter 😢

**Comment by numToStr** [comment]
> Yes it applies the filetype `swift` and then applies the filetype `ios`.

I think adding `ios` as a filetype will probably fix this(?)

**Comment by numToStr** [comment]
IMO there isn't any tangible benefit of adding support for sub-filetype. Most people (incl. myself) probably weren't even aware of this feature. Treesitter also doesn't work with sub-filetype (understandable as it doesn't need to). If anyone wants to add support for this they can do that themselves like this

```lua
local ft = require('Comment.ft')

-- NOTE: I am assuming that `ios.swift` is same as `swift` 
ft.set('ios.swift', ft.lang('swift'))
```

Thoughts? @jandamm

**Comment by jandamm** [comment]
I see the advantage that Comment.nvim would work out of the box like vim.
And like people knowing sub filetypes would expect it to work.

Apart from that there isn't that big of an issue defining the filetype myself.

**Comment by numToStr** [comment]
> Apart from that there isn't that big of an issue defining the filetype myself.

Thanks, I appreciate that.

But If a bunch of people starts complaining about sub-filetypes then I would consider adding it till then I am going to close this :)

**Comment by jandamm** [comment]
For completeness:
```lua
local ft = require('Comment.ft')
ft.set('ios.swift', ft.get('swift'))
```

**Comment by numToStr** [comment]
I was wondering about this the other day, and I changed my mind. So, I'll be adding this as a feature. My solution is different than yours, I hope you'll like it XD

**Comment by jandamm** [comment]
> My solution is different than yours, I hope you'll like it

This is actually his I thought it should work 👍
Apparently I wasn't articulating it well enough 😅
