### ISSUE TITLE
Calling the linewise comment toggle on multiple lines with visual mode loses selection

### ISSUE THREAD

**Issue by jmiln** [numToStr/Comment.nvim#113]
If you select multiple lines in visual mode, then run the command documented in the api page (Shown below), then typing `gv` to reselect previous selection only reselects the starting line, and not the entire selection.

This happens when typing in the lua command manually too, not just when having it mapped.

```lua
-- Linewise toggle using C-/
map('x', '<C-_>', '<ESC><CMD>lua require("Comment.api").toggle_linewise_op(vim.fn.visualmode())<CR>')
```

**Comment by numToStr** [comment]
> If you select multiple lines in visual mode, then run the command documented in the api page (Shown below), then typing `gv` to reselect previous selection only reselects the starting line, and not the entire selection.

Yes, the API functions does not preserve marks by default.

Try

```lua
-- Linewise toggle using C-/
map('x', '<C-_>', '<ESC><CMD>lua require("Comment.api").locked.toggle_linewise_op(vim.fn.visualmode())<CR>')
```

**Comment by jmiln** [comment]
Awesome, that works perfectly. 
Thanks!
