### ISSUE TITLE
Why does `opleader` create mapping in both normal and visual mode?

### ISSUE THREAD

**Issue by melkster** [numToStr/Comment.nvim#117]
Why does `opleader` create a mapping in both normal _and_ visual mode? I noticed that the mapping I set for operator-pending mode appears as an `xmap` as well. Is there a specific reason for why it is set in visual mode as well? Is it even possible to perform an operator-pending command from visual mode?

From the README:

```lua
---LHS of operator-pending mappings in NORMAL + VISUAL mode
---@type table
opleader = {
    ---Line-comment keymap
    line = 'gc',
    ---Block-comment keymap
    block = 'gb',
},

```

**Comment by numToStr** [comment]
> Is there a specific reason for why it is set in visual mode as well? 

Because then in visual mode you will be able to do something like `V10jgc` to comment 10 lines in visual mode.

**Comment by melkster** [comment]
Ok I think see your point.

It sorta clashed with my setup because I wanted try using as `cm` as a trigger in normal mode and `<leader>c` in visual mode, but this caused `cm` to become an operator in visual mode as well which I didn't want.

I'll just use #98 to set up my mappings instead as you suggested in #104.
