### ISSUE TITLE
reselect-visual broken after (un)commenting that visual selection

### ISSUE THREAD

**Issue by Frydac** [numToStr/Comment.nvim#118]
I regularly use `gv` to reselect a previous visual selection, however after using a comment/uncomment on the selection, that doesn't work, it seems to select the first line of the previous selection.

I can imagine the text and thus selection area has changed after (un)commenting, but when I for example do line visual selection/comments, it seems natural to be able to reselect those lines again.
This is something that works with nerdcommenter for example, both for line selection and non-line selection.

**Comment by numToStr** [comment]
Are you saying that `gv` is not working with the default mappings? Or did you setup some custom keybindings?

**Comment by Frydac** [comment]
Indeed, I had remapped and that mapping was clashing with some other mapping for lsp functionality.
I removed the clashing mapping in my lsp on_attach and now it works as expected.

For future reference if ppl have a similar issue, my nvim.comment setup with packer:
```
        use { 'numToStr/Comment.nvim',
            config = function() require('Comment').setup({
                toggler = {
                    line = '<leader>c<leader>',
                },
                opleader = {
                    line = '<leader>c',
                },
                mappings = {
                    extended = true
                }
            }) end
        }
```
I use <space> as leader, then I can use my right thumb and my left digit to do comments, which feels better to me than `gc`
and I also had the following mapping in my lsp on_attach function which I copied from the lsp on_attach example:
```
    buf_set_keymap('n', '<space>ca', '<cmd>lua vim.lsp.buf.code_action()<CR>', opts)
```
Not sure I understand what goes wrong because of this, but I removed the lsp mapping and it works as expected now, good catch, thank you!
