### ISSUE TITLE
Comment.nvim isn't working.

### ISSUE THREAD

**Issue by chimmy-changa** [numToStr/Comment.nvim#121]
Hi, 

I'm unable to get this plugin to work.

I've added the below lines to my plugins.lua file in this path:  .config/nvim/lua/plugins.lua 
```
 use {
    'numToStr/Comment.nvim',
    config = function()
        require('Comment').setup()
    end
  }
```

Below is my file structure:
├── init.lua
├── init.vim.old
├── lua
│   └── user
│       ├── colorscheme.lua
│       ├── comment.lua
│       ├── gitsigns.lua
│       ├── keymaps.lua
│       ├── plugins.lua
└── plugin
    └── packer_compiled.lua

Using :PackerStatus, I verified that the plugin has been installed correctly.

I've also tried adding "require("Comment").setup()" to my init.lua file but didn't work.

Haven't faced this issue with other plugins.

Is there any mistake that I'm doing?

Thanks.

**Comment by numToStr** [comment]
What's inside your init.lua?

**Comment by chimmy-changa** [comment]
@numToStr , thanks for the quick response.

Here are the contents of my init.lua:
```
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.lualine"
require "user.cmp"
require "user.lsp"
require "user.telescope"
-- require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.toggleterm"
require "user.autopairs"
require "user.treesitter"

require("Comment").setup()

```

**Comment by arpangreat** [comment]
Well you called the setup function twice. Delete the setup function in plugins.lua file. And you will good to go :)

**Comment by numToStr** [comment]
If the above solution doesn't work. You can also ask other people on neovim matrix channel :)

**Comment by chimmy-changa** [comment]
@arpangreat , I think I did not commit the changes which had only 1 occurance of the setup() call. I'll push them now.

@numToStr , I've tried the entire workflow in an ubuntu docker container and I am still not able to get it to work.

**Comment by arpangreat** [comment]
You can check  `~/.cache/nvim` if it exists, if it is , then you found your whole cache directory.

**Comment by arpangreat** [comment]
Also can you specify , exactly where or what are the issues you are experiencing rn ?

**Comment by chimmy-changa** [comment]
@arpangreat , thanks for the quick response. I'm unable to get Comment.vim to work. No issue at all with other plugins.

**Comment by arpangreat** [comment]
Could you update your dotfiles rn ? And also where exactly you are getting issues while using the plugin, any screen shot or cast ?

**Comment by chimmy-changa** [comment]
Just pushed [here](https://github.com/chimmy-changa/temp_dotfiles).  Not sure exactly what screenshot. 

After installing all the plugins. I restart nvim. Then open ~/.config/nvim/init.lua file. 

When I press `gcc` nothing happens. nvim behaves as if the Comment.vim plugin has no effect.

**Comment by chimmy-changa** [comment]
@arpangreat , looks like it is working when I comment out other require's in my init.lua!

Probably a conflict of shortcuts ?  
I'll narrow down the problem and update here!

**Comment by arpangreat** [comment]
Well @chimmy-changa you can only comment out bufferline require , because it's causing the problem. Some how , the pcall function , catching bufferline as if it's a boolean. So resolve that and you good to go.

**Comment by chimmy-changa** [comment]
@arpangreat , just resolved it. 

Of all the mistakes that I can imagine doing, I made the stupidest one.

The timeoutlen in my options.lua file is 100ms. I'm taking a bit more than 100ms when typing `gcc` or `gbc`. If updated it to 200ms it works as expected.

Thanks for taking the time. Nice github profile btw. 

This is [me](https://github.com/diningPhilosopher64)

Do feel free to check out my dotfiles as well! Specially the stuff related to tmux under aliases. Still a work in progress.

All of it inspired by @primeagen.

**Comment by arpangreat** [comment]
Nice to meet you @chimmy-changa , but still when I ran your config file , I got an error as I specified , so still check it out.


And of course , I will look into that 😋
