### ISSUE TITLE
Toggle single like doesn't work for me

### ISSUE THREAD

**Issue by dmaizel** [numToStr/Comment.nvim#123]
All other functionality works perfectly fine (even toggling a comment on a single line in visual mode).
But toggling a single line in normal doesn't work, any ideas about what might cause this?

**Comment by numToStr** [comment]
https://github.com/numToStr/Comment.nvim/issues/121#issuecomment-1039873942?

**Comment by dmaizel** [comment]
> [#121 (comment)](https://github.com/numToStr/Comment.nvim/issues/121#issuecomment-1039873942)?

Thank you for the quick response, that solved the issue!
