### ISSUE TITLE
Make `[count]gcc` dot-repeatable

### ISSUE THREAD

**Issue by kiryph** [numToStr/Comment.nvim#125]
I have switched from [vim-commentary](https://github.com/tpope/vim-commentary) by tpope.

Motivation:

> This plugin has native treesitter support for calculating commentstring which works for multiple (injected/embedded) languages like Vue or Markdown. 

I miss the possibility to repeat `10gcc` with the dot `.`.

I have found following [comment](https://github.com/numToStr/Comment.nvim/issues/104#issuecomment-1017221468)

> `toggle_current_linewise_op` is dot-repeatable whereas `toggle_linewise_count` is not.

Is it possible to make `toggle_linewise_count` dot-repeatable as well?

In particular, at the moment the buffer is changed in a suprising way:

```
hello
world
hello
world
```

Press on first line `2gcc` and then move to third line to press `.`, you get:
```
/* hello */
/* world */

ello
world
```

A line is inserted and a character is removed. This does not feel like it is intended. vim-commentary handles this flawlessly:
```
/* hello */
/* world */
/* hello */
/* world */
```

**Comment by numToStr** [comment]
@kiryph `[count]gcc` and `[count]gbc` both doesn't support dot-repeat. I wasn't motivated enough to support that as I don't use them very often.

(I would like to assume this ticket as feature request not a bug)

**Comment by kiryph** [comment]
> It's already there https://github.com/numToStr/Comment.nvim#count-prefix

Oh my bad. Sorry.
