### ISSUE TITLE
Remove comment at the end of line

### ISSUE THREAD

**Issue by nkakouros** [numToStr/Comment.nvim#128]
Is it possible to delete a comment at the end of the current line? If not, would it be possible to consider adding this in a future release?

**Comment by nkakouros** [comment]
For instance, pressing a hypothetical mapping`gcd` while on the next line (`|` is the cursor position):

```
co|de_here  # comment here

OR

code_here # commen|t here
```

would delete the ` # comment here` part or at least the `# comment here` part (without the preceding spaces).

**Comment by numToStr** [comment]
This would be interesting to solve with treesitter (using text-objects) but without it, this would be way easier do this with combination of vim commands rather than having an specific feature just for deleting end of line comments.

- #11
- #22
