### ISSUE TITLE
Operator Pending mode confusion

### ISSUE THREAD

**Issue by hahuang65** [numToStr/Comment.nvim#134]
When pressing `gc` in quick succession, it becomes `g@`, which according to the keymapping, looks correct:

```
<Cmd>lua require("Comment.api").call("toggle_linewise_op")<CR>g@
```

My confusion though lies in the timing of keypresses. If I press `gc` but do it slowly, that's when it triggers `gc` instead of `g@`.
This, in turn, prohibits me accessing mappings like `gcA` or `gcO` if I press it too quickly.

What is the reason for this, and how can I fix/workaround it?

**Comment by numToStr** [comment]
It might be because of this https://github.com/numToStr/Comment.nvim/issues/115#issuecomment-1032290098
