### ISSUE TITLE
Support comments in nested (injected) code blocks 

### ISSUE THREAD

**Issue by numToStr** [numToStr/Comment.nvim#137]
Let's say in `markdown` if you have a code block like Lua (w/ vim) or vue (w/ CSS and JS) which can also have multiple child languages then only the commentstring from the parent lang will be used instead of using the commentstring of child language.

Suppose you have this code block *inside markdown* and if you try to comment `echo 1234` you'll get `--` instead of `"`

```lua
\```lua
use {
    'numToStr/Comment.nvim',
    config = function()
        require('Comment').setup()
        vim.cmd[[
            -- echo 1243
            norm! ggG
        ]]
    end
}
\```
````

And same with vue, commenting `color: red;` uses `<!-- -->` instead of `/* */`

```vue
\```vue
<style>
body {
  <!-- color: red; -->
}
</style>
\```
```

**Comment by kuntau** [comment]
@numToStr Does this mean we don't need [nvim-ts-context-commentstring ](https://github.com/JoosepAlviste/nvim-ts-context-commentstring) anymore?

**Comment by numToStr** [comment]
> Does this mean we don't need [nvim-ts-context-commentstring ](https://github.com/JoosepAlviste/nvim-ts-context-commentstring) anymore?

You already don't need it as treesitter is natively supported and the related PR just extends language detection to nested blocks.

Although you do need `nvim-ts-context-commentstring` if you want `jsx` support but that could also change soon

- #133
