### ISSUE TITLE
Some motions don't accept a count (deviates from commentary)

### ISSUE THREAD

**Issue by hermitmaster** [numToStr/Comment.nvim#139]
For example `2gcap` only comments a single paragraph, where I would expect it to do two. gcap and gcip are the two that I have noticed.

**Comment by numToStr** [comment]
Is possible to select 2 paragraphs using `2vip`?

**Comment by hermitmaster** [comment]
Valid question. The answer is no. I just expected it to work because it works with commentary. Closing.
