### ISSUE TITLE
[Feature request] toggle_visual()

### ISSUE THREAD

**Issue by RaafatTurki** [numToStr/Comment.nvim#14]
This is an amazing commenting plugin, the only reason stopping me form using it is the fact that it does the mappings for you
now I don't use motions to comment but visual commenting is a must.

I can do single lines with mapping `:lua require "Comment".toggle()<CR>` however as far as I know there is no equivalent to that function to visual mode.

**Comment by numToStr** [comment]
Oh, Now I get it. To be honest, I might not support that directly but I can give you the building blocks to do it. Will this be ok?

**Comment by numToStr** [comment]
Great. I am making some function public so that anyone can use as they please.

**Comment by numToStr** [comment]
No, not that. The function that parses commentstring.

**Comment by numToStr** [comment]
@RaafatTurki Here you go
```lua
local Ut = require('Comment.utils')
local Op = require('Comment.opfunc')

function _G.__toggle_visual(vmode)
    local lcs, rcs = Ut.unwrap_cstr(vim.bo.commentstring)
    local scol, ecol, lines = Ut.get_lines(vmode, Ut.ctype.line)

    Op.linewise({
        cfg = { padding = true, ignore = nil },
        cmode = Ut.cmode.toggle,
        lines = lines,
        lcs = lcs,
        rcs = rcs,
        scol = scol,
        ecol = ecol,
    })
end

vim.api.nvim_set_keymap(
    'x',
    '<Leader>l',
    '<ESC><CMD>lua __toggle_visual(vim.fn.visualmode())<CR>',
    { noremap = true, silent = true }
)
```

**Comment by RaafatTurki** [comment]
Works fantastically. Since you're not sure you want to implement this yourself would a PR be welcome (a more expansive one that handles block comments)?
Thanks a bunch

**Comment by numToStr** [comment]
A wiki might be better suited for this as other users might not want this. We can also add some other comments combinations like normal+block. What do u say?

**Comment by RaafatTurki** [comment]
such customization would be really nice no matter how it's achieved, so yeah perhaps a wiki detailing how to build your own comment function would be pretty cool

**Comment by numToStr** [comment]
That's it then. I've enabled wiki for the project, so users can add their own customized functions or I'll add it when I get the chance. Thanks, @RaafatTurki for bringing this up, this issue made this plugin more amazing :)

**Comment by drmohundro** [comment]
Not sure when this came, but now all that has to be done is:

```lua
vim.api.nvim_set_keymap(
    'x',
    '<Leader>l',
    '<esc><CMD>lua require("Comment.api").toggle_linewise_op(vim.fn.visualmode())<CR>',
    { noremap = true, silent = true }
)
```

Thanks!
