### ISSUE TITLE
Packer issues Warning

### ISSUE THREAD

**Issue by mkohlhaas** [numToStr/Comment.nvim#140]
After latest update Comment.nvim is not working any more. Also Packer issues a warning message. I'm using a standard setup as outlined in the Readme. No customizations.

```
use {
    'numToStr/Comment.nvim',
    config = function()
        require('Comment').setup()
    end
}
```

[WARN  So 17 Apr 2022 10:17:18 CEST 5492877106098] ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:566: Potential breaking change in commit f9df984 of numToStr/Comment.nvim

**Comment by numToStr** [comment]
Yes, I've merged a feature in https://github.com/numToStr/Comment.nvim/commit/f9df9847ca403cee7124d862249c02916e773d03 that is breaking for 0.6 users. So I request you to follow https://github.com/numToStr/Comment.nvim/releases/tag/v0.6 until you upgrade to 0.7

**Comment by mkohlhaas** [comment]
Hi Vikas,

you're right. I'm having [troubles updating to latest nvim](https://github.com/void-linux/void-packages/pull/36704).

Just tested with appimage. Everything's fine. Thank you! Very nice plugin! I use it daily.

**Comment by numToStr** [comment]
@mkohlhaas I am glad you resolved it :)
