### ISSUE TITLE
index field 'keymap' (a nil value)

### ISSUE THREAD

**Issue by Ruixi-rebirth** [numToStr/Comment.nvim#141]
![image](https://user-images.githubusercontent.com/75824585/163709313-bed57507-2082-466a-8730-0c4008e45ca9.png)

![image](https://user-images.githubusercontent.com/75824585/163709446-708063f5-0a8d-4340-8e96-c9dd51b51608.png)

**Comment by carlosala** [comment]
same here, looks like latest commit broke something

**Comment by numToStr** [comment]
https://github.com/numToStr/Comment.nvim/releases/tag/v0.6

**Comment by carlosala** [comment]
oh I just read the PR. Ok, nice, let's stick in tag `v0.6` until [arch repos](https://archlinux.org/packages/community/x86_64/neovim) update the package. Thanks! 👍🏻

**Comment by Ruixi-rebirth** [comment]
I updated the neovim version and everything is fine

**Comment by numToStr** [comment]
Yes, I've merged a feature in https://github.com/numToStr/Comment.nvim/commit/f9df9847ca403cee7124d862249c02916e773d03 that is breaking for 0.6 users. So I request you to follow [v0.6 (release)](https://github.com/numToStr/Comment.nvim/releases/tag/v0.6) until upgrading to 0.7
