### ISSUE TITLE
The latest update broke my config: E5113: Error while calling lua chunk: .../site/pack/packer/start/Comment.nvim/lua/Comment/api.lua:237: attempt to index field 'keymap' (a ni l value)

### ISSUE THREAD

**Issue by quantumfate** [numToStr/Comment.nvim#142]
`Error detected while processing /home/leonch/.config/nvim/init.lua:
E5113: Error while calling lua chunk: .../site/pack/packer/start/Comment.nvim/lua/Comment/api.lua:237: attempt to index field 'keymap' (a ni
l value)
stack traceback:
        .../site/pack/packer/start/Comment.nvim/lua/Comment/api.lua:237: in function 'setup'
        /home/leonch/.config/nvim/lua/user/comment.lua:6: in main chunk
        [C]: in function 'require'
        /home/leonch/.config/nvim/init.lua:9: in main chunk
Error detected while processing /home/leonch/.local/share/nvim/site/pack/packer/start/Comment.nvim/after/plugin/Comment.lua:
E5113: Error while calling lua chunk: .../pack/packer/start/Comment.nvim/after/plugin/Comment.lua:1: attempt to index field 'keymap' (a nil
value)
stack traceback:
        .../pack/packer/start/Comment.nvim/after/plugin/Comment.lua:1: in main chunk`
        
Removing the plugin from init.lua doesn't fix the error but removing the plugin from ~.local/share/nvim/site/pack/packer/start/ does

My config

https://github.com/quantumfate/quantumvim.git

**Comment by numToStr** [comment]
duplicate of #141
