### ISSUE TITLE
Issue with injected language

### ISSUE THREAD

**Issue by gegoune** [numToStr/Comment.nvim#144]
Hey, have noticed that if you have a cursor inside string such as (lua file example)

```lua
vim.cmd 'stopinsert!'
```

commanding `gcc` leads to incorrectly commented out line:

```lua
" vim.cmd 'stopinsert!'
```

I am not quite sure if I would expect it to turn to 
```lua
vim.cmd '" stopinsert!'
```

or simply do nothing (perhaps it should comment out injected code, as it would make sense within multilane blocks). But correct behaviour is surely wrong.

(thanks for great plugin!)

**Comment by numToStr** [comment]
This is kinda similar to #135

Could you try to recreate the same with `vim.cmd[[stopinsert!]]` or `vim.cmd('stopinsert!')`?

**Comment by gegoune** [comment]
Both work fine, as in, comments out entire line with `-- `.

**Comment by numToStr** [comment]
As I suspect, the thing with `gcc` is that it takes the range from the current cusor possition to the end of line and uses that to detects the language.

So with `vim.cmd 'stopinsert!'`, `gcc` was only able to detect vim and used `"` as the commentstring. But with `vim.cmd('stopinstert!')`, the last char i.e `)` is Lua so `gcc` then used `---`

This situation, two languages on the same line, will always be ambiguous. And I don't even know whether is this something that needs to be fixed or not.

**Comment by numToStr** [comment]
I am closing this for now. As I don't know a solution that'll work in every case. If anyone figures this out feel free to reply or even raise a PR :)
