### ISSUE TITLE
Commands not working in latest nightly

### ISSUE THREAD

**Issue by AckslD** [numToStr/Comment.nvim#147]
After updating my neovim and plugins, comment.nvim stopped working. The keybinds are there but nothing happens when pressing them, and also not if doing eg `:normal gcc`. I also tried with the following minimal config:
```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
    require('packer').startup {
        {
            'wbthomason/packer.nvim',
            'numToStr/Comment.nvim',
        },
        config = {
            package_root = package_root,
            compile_path = install_path .. '/plugin/packer_compiled.lua',
            display = { non_interactive = true },
        },
    }
end
_G.load_config = function()
    require("Comment").setup()
end
if vim.fn.isdirectory(install_path) == 0 then
    print("Installing dependencies.")
    vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by numToStr** [comment]
#115?

**Comment by AckslD** [comment]
I checked that but my `timeoutlen` is 500 and even if it would be smaller I think `:normal gcc` would still work?

**Comment by numToStr** [comment]
Yes, `gcc` should work. I am not sure what to tell you then, plugin is working fine for me and I am also on nightly.

(I'll try to recreate the issue from the given snippet tomorrow)

**Comment by AckslD** [comment]
Hmm strange, thanks for the response anyway! I'll let you know if I figure out what is going wrong.

**Comment by AckslD** [comment]
It now started working, unfortunately I really have no clue what changed. Sorry for a very non-descriptive issue. Hopefully it stays this way, otherwise I'll try to dig a bit deeper next time.
