### ISSUE TITLE
Function to comment currently selected block

### ISSUE THREAD

**Issue by WhyNotHugo** [numToStr/Comment.nvim#151]
I want to configure a mapping to comment out a selected block when on visual mode.

Based on the lua API docs, I've tried this:

```lua
vim.keymap.set("x", "<Leader>c", function()
  require("Comment.api").locked.toggle_linewise_op(vim.fn.visualmode())
end)
```

But when selecting a few lines and pressing `<Leader>c`, the whole file is commented out.

I've also tried this version:

```lua
vim.keymap.set("x", "<Leader>c", function()
  require("Comment.api").toggle_linewise_op(vim.fn.visualmode())
end)
```

But this messes things up; it comments out only 1 or 2 of three selected lines, and sometimes messes up their order.

**Comment by numToStr** [comment]
To be able to comment the selection, you have to first exit/esc the visual mode. Then only the visual marks i.e `'>` `'<` get populated with the selected range.

So your keymaps won't work until you first exit the visual mode. But you can use the following keymap which will do all that for you.

```lua
vim.keymap.set('x', '<leader>c', '<Plug>(comment_toggle_linewise_visual)')
```

**Comment by lyonelz96** [comment]
@WhyNotHugo  The keymap described in the [Lua API Docs](https://github.com/numToStr/Comment.nvim/blob/master/doc/API.md#%EF%B8%8F-usage) and the one above work just fine...

That being said I'm stubborn af and I wanted my darn lua function lol so I found a way to replicate that forsaken '<ESC>'. Here's the snippet:

```lua
vim.keymap.set('v', '<leader>cb', function()
	local key = vim.api.nvim_replace_termcodes('<ESC>', true, false, true)
	vim.api.nvim_feedkeys(key, 'nx', false)
	require('Comment.api').toggle_linewise_op(vim.fn.visualmode())
end)
```
