### ISSUE TITLE
prehook not working for jsx files

### ISSUE THREAD

**Issue by RyanzpLee** [numToStr/Comment.nvim#153]
I have added the prehook field into the setup, and I am following the instructions documented in the README and installed `"JoosepAlviste/nvim-ts-context-commentstring"`

However, when I am in a jsx file, and I try to comment out the html in the jsx, it only uses the `//` comment and does not wrap it in braces as expected. [Here is the link to my plugins](https://github.com/RyanzpLee/dotfiles/blob/main/nvim/lua/user/plugins.lua) and [here is the Comment.nvim setup](https://github.com/RyanzpLee/dotfiles/blob/main/nvim/lua/user/plugins/comment.lua)

I'm not sure what I'm doing wrong, but I would love for this to work properly. Any help would be appreciated!
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/69594457/165503414-f88936b4-0b7b-40ad-af85-18e742051040.png">

**Comment by numToStr** [comment]
Check whether `calculate_commentstring()` is returning the correct commentstring or not? It should be `{/*%s*/}`

**Comment by numToStr** [comment]
I am going to close this for now. If you face this again feel free to open it. Also, I am working on native `jsx` support, I'll appreciate it If you can give your feedback on it :)

- #133

**Comment by RyanzpLee** [comment]
I appreciate the help, I ended up using this configuration from [the nvim-ts-util-context-commentstring repo](https://github.com/JoosepAlviste/nvim-ts-context-commentstring#commentnvim) and it's working great now.

Also native jsx support sounds fantastic. I love your plugin!

**Comment by bpingris** [comment]
Hey @RyanzpLee how did you manage to get this working?
I tried to follow the instructions mentionned in link you shared but it's still not working, I keep having `//` appended to jsx tags.
I took a look at your dotfiles and tried to copy/paste your config and reload neovim but it's still the same

Not really sure what I could be missing 🤔
