### ISSUE TITLE
[Feature] comment multiple lines

### ISSUE THREAD

**Issue by JasonWong97** [numToStr/Comment.nvim#157]
I'm new to vim. Thanks for the useful plugin.
I found this method to comment multiple specific lines.
`:1,4s/^/#`

But it needs to press shift multiple times.
Is there a way to comment like this?:
`:1,4gcc`

**Comment by numToStr** [comment]
> `:1,4gcc`

`gcc` is a keybinding not a ex-command so this won't work. You need to add before `norm` before `gcc`. So the final command will look like this `:1,4norm gcc`
