### ISSUE TITLE
[Feature] uncomment current block

### ISSUE THREAD

**Issue by JasonWong97** [numToStr/Comment.nvim#158]
I'm new to vim. Thanks for the useful plugin.
I wonder if there is a way to uncomment current block.
like:
`:guc`

The current block means the code segment where the cursor is located, separated by non-comment lines.
If the cursor is in line `#cc`, these three lines could be uncommented.

```
# aa

#bb 
#cc
#dd

#ee
```

**Comment by numToStr** [comment]
This is tracked in
- #11
- #22
