### ISSUE TITLE
WARN: nvim-treesitter.ts_utils.get_node_text is deprecated: use vim.treesitter.query.get_node_text

### ISSUE THREAD

**Issue by fgheng** [numToStr/Comment.nvim#160]
![image](https://user-images.githubusercontent.com/50551377/168210273-0bdc1045-9aea-443c-b9be-9e517358f6fe.png)

**Comment by numToStr** [comment]
I am pretty sure that I am not using `nvim-treesitter` in `Comment.nvim` 🤷🏻
