### ISSUE TITLE
setting comment for filetype doesn't work

### ISSUE THREAD

**Issue by RishabhRD** [numToStr/Comment.nvim#163]
Hi, Thanks for the great plugin.
I have this config:
```
local ft = require "Comment.ft"
ft.set("lua", { "-- hello %s", "--[[ hello %s]]" })
```

However, while commenting using keymap doesn't follow the filetype rule and does the default commenting. Do, I need to do something else?

**Comment by numToStr** [comment]
> Do, I need to do something else?

No, this should work without any problem.

**Comment by numToStr** [comment]
I've just tested it and it works fine for me. So I am closing it for now.
