### ISSUE TITLE
Commenting out the first line of CSS inside of an html file is broken

### ISSUE THREAD

**Issue by s4my** [numToStr/Comment.nvim#164]
Hi @numToStr, in the process of trying to comment out a block of css inside of an html file (inside of <style> tag), the html comment string is used `<!-- %s -->` instead of the css comment string `/* %s */`. this bug happens for both linewise and blockwise comments. 

``` html 
<!DOCTYPE html>
<html>
    <head>
        <title>Comment.nvim bug</title>
        <style>
            <!-- body { -->
                background: #f7f7f8;
                font-family: Inter,Roobert,Helvetica Neue,Helvetica,Arial,sans-serif;
            }
        </style>
    </head>
    <body>
</html>
```
if you start your selection from the second line after the *<style>* tag the plugin works perfectly.
``` html
<!DOCTYPE html>
<html>
    <head>
        <title>Comment.nvim bug</title>
        <style>
            body {
            /*     background: #f7f7f8; */
            /*     font-family: Inter,Roobert,Helvetica Neue,Helvetica,Arial,sans-serif; */
            /* } */
        </style>
    </head>
    <body>
</html>
```

**Comment by numToStr** [comment]
This is expected and already discussed. https://github.com/numToStr/Comment.nvim/pull/62#issuecomment-972790418

**Comment by s4my** [comment]
ok, waiting for the fix i guess :)

**Comment by numToStr** [comment]
@s4my To be clear, this is also listed as limitation in the README so I don't think there will be any fix for this issue.
