### ISSUE TITLE
WhichKey shows conflicts with default keybindings

### ISSUE THREAD

**Issue by matu3ba** [numToStr/Comment.nvim#167]
## WhichKey: checking conflicting keymaps
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"gb"**
  - INFO: rhs: `<Plug>(comment_toggle_blockwise)`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"gc"**
  - INFO: rhs: `<Plug>(comment_toggle_linewise)`

Would be nice to add a hint how to disable this with note on the default keybindings.

see also https://github.com/linty-org/key-menu.nvim/pull/8 for the great effort.

**Comment by numToStr** [comment]
> Would be nice to add a hint how to disable this with note on the default keybindings.

I am not sure, what to disable here(?). As I don't use whichkey so I have no idea what to do here. But if you want, you can disable all the mappings by adding `mappings = false` to setup config

**Comment by Jetandarkumar** [comment]
I have copied comment.lua from your config but still the mappings are not working!! What do I do? The plugin is not giving any errors? The path in the Packer config is also correct.
Code from comment.lua --> require('Comment').setup({
    pre_hook = function(ctx)
        return require('Comment.jsx').calculate(ctx)
    end,
})

**Comment by numToStr** [comment]
@Jetandarkumar What mappings are not? Are you talking about whichkey? If not please have a look https://github.com/numToStr/Comment.nvim/issues/115

**Comment by numToStr** [comment]
I am closing this as this is not really a issue with the plugin.

**Comment by zippeurfou** [comment]
@numToStr I think he is referring to the `:checkhealth` command where `which-key` tells you if any of your mapping has conflict and in this case this plugin seems to display a conflict.
<img width="470" alt="Screenshot 2023-01-19 at 1 40 08 PM" src="https://user-images.githubusercontent.com/4520383/213532036-ddbe64a4-b928-44b8-9f0f-adac549728fd.png">
So it is not really about changing your keymap but somehow something create a conflict there.
