### ISSUE TITLE
Not working on NixOS

### ISSUE THREAD

**Issue by ObsidianChickenz** [numToStr/Comment.nvim#168]
I have no idea why, as I have everything set up correctly. I can post any extra info as needed, but I have no idea where to even begin.

**Comment by numToStr** [comment]
#115

**Comment by ObsidianChickenz** [comment]
My timeoutlen is set to 1000 and it still doesn't work. Should I set it higher?

**Comment by ObsidianChickenz** [comment]
On NixOS, you install Neovim plugins via their builtin package manager, Nix. It installs the plugin in the Start or Opt folder depending on if the plugin is lazyloaded or not. However, it installs the plugin as `comment.nvim` instead of `Comment.nvim`. Could this change something?

**Comment by numToStr** [comment]
That, I have no idea. You should ask other people that have similar config as yours.

**Comment by ObsidianChickenz** [comment]
A fix has been found! I have to run `:runtime after/plugin/Comment.lua` because `:packadd` doesn't automatically source the after directory in the opt directory. Someone in the thread called the use of the after directory an abuse, so I'm wondering why that is. What is the after directory used for?
PS: Since I found a working solution, I'll mark this as closed.

**Comment by numToStr** [comment]
> A fix has been found! I have to run `:runtime after/plugin/Comment.lua` because `:packadd` doesn't automatically source the after directory in the opt directory. Someone in the thread called the use of the after directory an abuse

Hmmm very interesting. I never thought that this might well be an anti-pattern or something. You said you lazyload the plugin, could you try an sync load the plugin? And tell me whether this issue still there or not. As I use `packer.nvim` and do lazyload. I never faced this issue myself.

> so I'm wondering why that is. What is the after directory used for?

I am using it for setting up `<Plug>` mappings.

**Comment by numToStr** [comment]
Hi @ObsidianChickenz, you might not need that workaround after 4818a4c2ecf64ace6358b81073ad5d76f657953d :)
