### ISSUE TITLE
Bug with comment_toggle_linewise_visual in ruby files

### ISSUE THREAD

**Issue by mario-amazing** [numToStr/Comment.nvim#171]
I have a constantly moving string bug, when I call <Plug>(comment_toggle_linewise_visual) -> vgc -> vgc in ruby file

https://user-images.githubusercontent.com/9537753/174396499-c31f45ca-c49e-4b35-be3d-c81503f411b5.mov

**Comment by numToStr** [comment]
I am not sure what you are talking about(?)

**Comment by mario-amazing** [comment]
@numToStr <Plug>comment_toggle_linewise_visual add comment with space `#<space>` but after uncomment with the same function, it is remove `#` but not  added `space`

**Comment by numToStr** [comment]
I checked everything on a ruby file and I am not able to reproduce the issue.

**Comment by numToStr** [comment]
I am closing this for now. Feel free to reopen, if you are still facing the issue.
