### ISSUE TITLE
How to use the same style for line and block comment ?

### ISSUE THREAD

**Issue by ievgenii-shepeliuk** [numToStr/Comment.nvim#172]
Hello, excuse me for ambigous title - let me explain the issue below.

I'm using [vim-helm](https://github.com/towolf/vim-helm) plugin that set custom filetype (`helm`) and overrides `commentstring` for files with `*.yaml` extensions, but that are matching [a certain pattern](https://github.com/towolf/vim-helm/blob/master/ftdetect/helm.vim#L4).

When I switched to this plugin - I am noticing that line comments are still using `# ..` style ( I believe it comes from initial setup for `*.yaml` files). Block comments are working fine both in normal and visual mode.

Could you please explain - how to make line comments to use `commentstring` from the `vim-plug`. 
I've tried overriding `ft` table - but it didn't work. 

Eventually I've added a pre-hook
```lua
require('Comment').setup {
    pre_hook = function(ctx)
        if vim.bo.filetype == 'helm' then
            return '{{/* %s */}}'
        end
    end
}
```

Although pre-hook is solving my issue - but it feels like it should not be that complicated and the `vim-plug` 's `commentstring` should be respected automatically.

Btw, I've used [this plugin](https://github.com/terrortylor/nvim-comment) before and there the line comment was considering `commentstring`. Now I am switching to this plugin for obtaining `treesitter` support.

**Comment by numToStr** [comment]
Can you check the `filetype` and `commenstring`? This plugin doesn't contain `helm` comment string, so it should be using native `commentstring` by default which will be used for both line and block comments

**Comment by eshepelyuk** [comment]
> Can you check the `filetype` and `commenstring`? This plugin doesn't contain `helm` comment string, so it should be using native `commentstring` by default which will be used for both line and block comments

Sure i did it as a 1st debug steps. both are set to expected values: `helm` for filetype and commentstring to `{{/* %s */}}`.

Alos, addng helm to ft table didnt help. But I'be noticed if i override ft for `yaml` that comment style is picked up, so looks like this plugin uses `yaml` comments even if filetype is set to smth different.

PS: there are typos in previous messages, I used `vim-plug` but i should have used `vim-helm`.

**Comment by numToStr** [comment]
Ahhh, I get it what's happening. It's because treesitter doesn't consider `filetype` and is detecting `yaml` as a language for the helm file. And unfortunately to override the treesitter you need to use `pre_hook`.

**Comment by numToStr** [comment]
This will always be an issue for `helm` like filetype which differs (in `commentstring`) from the actual filetype (i.e., `yaml`) as treesitter always gives the parser's name which is attached to the buffer.

**Comment by ievgenii-shepeliuk** [comment]
> This will always be an issue for `helm` like filetype which differs (in `commentstring`) from the actual filetype (i.e., `yaml`) as treesitter always gives the parser's name which is attached to the buffer.

Just an assumption: since there's no treesitter parser for `helm` exists (at least for now) - maybe this plugin  can not invoke treesitter at all in similar cases and rely completely on `commentstring` registered for a buffer's `filetype` ?

**Comment by ievgenii-shepeliuk** [comment]
Also as a more rough workaround option #2 - maybe you can introduce a table of filetypes that should not be using tressitter at all ? So it's easier to add a filetype than writing a pre hook.
wdyt ?

**Comment by numToStr** [comment]
> maybe this plugin can not invoke treesitter at all in similar cases and rely completely on commentstring registered for a buffer's filetype ?
>
> maybe you can introduce a table of filetypes that should not be using tressitter at all ? So it's easier to add a filetype than writing a pre hook.
wdyt ?

Both of these are not optimal because **the cost of maintenance is more** than having the userland workaround for couple of filetype. Remember, the workaround is only needed for the filetype whose commentstring differs from the actual filetype.

**Comment by ievgenii-shepeliuk** [comment]
Hello

This is a diff that solves the issue

```diff
diff --git a/lua/Comment/ft.lua b/lua/Comment/ft.lua
index fb1d9e7..9380749 100644
--- a/lua/Comment/ft.lua
+++ b/lua/Comment/ft.lua
@@ -147,7 +147,8 @@ end
 function ft.calculate(ctx)
     local buf = A.nvim_get_current_buf()
     local ok, parser = pcall(vim.treesitter.get_parser, buf)
-    local default = ft.get(A.nvim_buf_get_option(buf, 'filetype'), ctx.ctype)
+    local default_lang = A.nvim_buf_get_option(buf, 'filetype')
+    local default = ft.get(default_lang, ctx.ctype)

     if not ok then
         return default
@@ -160,6 +161,9 @@ function ft.calculate(ctx)
         ctx.range.ecol,
     }):lang()

+    if lang ~= default_lang then
+      return default
+    end
     return ft.get(lang, ctx.ctype) or default
 end
 ```
 
 Would you like to accept a PR ?

**Comment by numToStr** [comment]
What about embedded language?

**Comment by ievgenii-shepeliuk** [comment]
> What about embedded language?

Embedded languages are only exist for treesitter based parsers, right ?

**Comment by numToStr** [comment]
> Embedded languages are only exist for treesitter based parsers, right ?

Yes, like codeblocks in markdown.

**Comment by numToStr** [comment]
IMO `pre_hook` can be used as an override for treesitter so there is no point in having a dedicated feature for overriding treesitter for couple of filetypes. As for your use case you can reduce that to just one line.

```lua
require('Comment').setup {
    pre_hook = function(ctx)
        return vim.bo.filetype == 'helm' and vim.bo.commenstring
    end
}
```

**Comment by ievgenii-shepeliuk** [comment]
Dear @numToStr 
It took me 4 hours to figure out the issue and come up with a solution using pre hook :((
I don't like other peoples to have the same experience and waste their time on reading source code and researching lua for creating additional configuration.

I'd like this plugin to shine even more and be as easy as possible to adapt.
It's the only reason I came up with my suggestions.

So, my last try 

```diff
diff --git a/lua/Comment/ft.lua b/lua/Comment/ft.lua
index fb1d9e7..3872898 100644
--- a/lua/Comment/ft.lua
+++ b/lua/Comment/ft.lua
@@ -147,7 +147,8 @@ end
 function ft.calculate(ctx)
     local buf = A.nvim_get_current_buf()
     local ok, parser = pcall(vim.treesitter.get_parser, buf)
-    local default = ft.get(A.nvim_buf_get_option(buf, 'filetype'), ctx.ctype)
+    local default_lang = A.nvim_buf_get_option(buf, 'filetype')
+    local default = ft.get(default_lang, ctx.ctype)

     if not ok then
         return default
@@ -160,7 +161,12 @@ function ft.calculate(ctx)
         ctx.range.ecol,
     }):lang()

-    return ft.get(lang, ctx.ctype) or default
+    local has_ts_parser = require('nvim-treesitter.parsers').has_parser(lang)
+    if lang ~= default_lang and has_ts_parser then
+      return ft.get(lang, ctx.ctype)
+    else
+      return default
+    end
 end
 ```
