### ISSUE TITLE
Packer config is not executed, found solution

### ISSUE THREAD

**Issue by herrbischoff** [numToStr/Comment.nvim#175]
### Environment

```
$ nvim -v
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by macports@bigsurx.internal.macports.net

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/local/share/nvim"

Run :checkhealth for more info
```

```
$ git log
commit 4086630ce2aaf76b2652516ee3169f0b558f6be1 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Richard Herron <richard.c.herron@icloud.com>
Date:   Wed Jun 29 13:47:35 2022 -0400

    feat: add `stata` support (#173)

    Stata docs: https://www.stata.com/manuals13/pcomments.pdf
```

### Issue

When setting the plugin up via packer, like documented

```lua
use {
    'numToStr/Comment.nvim',
    config = function()
        require('Comment').setup()
    end
}
```

I cannot get the plugin to work, neither `:normal gcc` nor any key command works. In fact, it appears the `setup()` method is not executed at all.

When I remove the wrapping function

```lua
use {
    'numToStr/Comment.nvim',
    config = require('Comment').setup()
}
```

everything works as expected.

This is not specific to this plugin. I have run into the issue with all plugin configurations via packer. So this is just a heads-up that this may occur.

**Comment by numToStr** [comment]
If you are facing a particular problem with every plugin then it's a problem with your configuration or packer.nvim.

**Comment by herrbischoff** [comment]
You are correct of course. Please excuse for not being precise enough in my wording. The reason for opening this issue is that this plugin is the only one I use which requires running a method via `config`. The other instances are loading a Lua config file with keymaps and settings for the respective plugin. I observed the same behavior there, a surrounding function declaration lead to Neovim/packer silently ignoring its content.

So I'm with you regarding the assessment, just thought I'd make a note here. I definitely could have been clearer. I'm going to take the issue to the packer community. I can leave the issue up and link any news here — or simply close it. Your call.
