### ISSUE TITLE
[Bug] Mapping for toggle comment in visual mode is defined in opleader

### ISSUE THREAD

**Issue by gutyina70** [numToStr/Comment.nvim#182]
A modified chunk of the template config (so the maps in **toggler** and **opleader** doesn't share the same *gc* sequence)
```
toggler = {
    line = '<space>bt',
    block = '<space>bT',
},
opleader = {
    line = '<space>bo',
    block = '<space>bO',
},
```
Due to this bug, to toggle comment in visual mode, you need to press `<space>bo` which is defined in the **opleader**. Pressing `<space>bt` in visual mode has no effect.

Changing `opleader` to `toggler` at [api.lua](https://github.com/numToStr/Comment.nvim/blob/master/lua/Comment/api.lua#L264-L265) fixes this issue, but might break for some people who are already used to this mapping.

**Comment by numToStr** [comment]
The behaviour you are taking about is expected. IDK what's the problem here?

**Comment by gutyina70** [comment]
My goal is to have the same map for toggling comments in both normal and visual mode. The expected solution for this would be to change the maps in **toggler**, but as I said, **it has no effect in visual mode**.
So to achive this goal I need to change the maps for **opleader**, which doesn't make sense, since in visual mode it is not operator pending.
And by changing the maps for **opleader** and **toggler** to the same keys, in normal mode I have to wait for the operator to stop for toggle commenting.

If this is really expected and not a misunderstanding, please tell me how to toggle comment in normal mode and visual mode **with the same keymaps**.

**Comment by numToStr** [comment]
This topic is already discussed couple of times https://github.com/numToStr/Comment.nvim/issues/104 https://github.com/numToStr/Comment.nvim/issues/117.

Currently you can't setup visual and op-pending keymaps differently but you can create new ones with https://github.com/numToStr/Comment.nvim/blob/master/doc/plugs.md

I am still not sure how to solve this natively without resorting to workarounds. If you have any ideas on how to improve the keymaps setup then I'll be glad to hear it :)

**Comment by gutyina70** [comment]
Thanks for linking the other issues and the docs, it helped me understand this issue better.

People were confused about operator pending maps in VISUAL mode including myself. `opleader` defines operator maps, so it is an **operator-pending map** in NORMAL, but an **operator map** in VISUAL mode. Clarifying this in the [readme configuration section](https://github.com/numToStr/Comment.nvim/blob/master/README.md#configuration-optional) would be nice.

Currently there are no maps defined for `toggler` in VISUAL mode (despite the readme saying that), so what about using the same maps for it as for `opleader` uses? But this solution breaks the default config, since when pressing `gc` in VISUAL mode, vim is waiting for another key since `gcc` is defined as well. It's probably possible to only create VISUAL maps for `toggler` only if it doesn't confict with `opleader`, but it sounds cumbersome to actually do.

**Comment by numToStr** [comment]
To be clear, I won't change the default keymaps as this breaks the default behavior of the plugin which I personally don't want. I'll wait for a solution which is extensible and where I don't have to expose configs of every keymap's LHS that is provided by the plugin.

**Comment by numToStr** [comment]
I am going to close this for now as I don't have a proper solution for this now and I don't intend to change the defaults anytime soon :)
