### ISSUE TITLE
htmldjango block comments 

### ISSUE THREAD

**Issue by farfanoide** [numToStr/Comment.nvim#187]
hi there, I'm trying to add line and block comments with the following code:

```lua
local comment_ft = require('Comment.ft')
comment_ft.set("htmldjango", { "{# %s #}", "{% comment %}%s{% endcomment %}" })
```
it works nicely on line comments however for block comments, when I try a multiline text object like a paragraph the first part of the comment is incorrectly formatted like `{ comment }` instead of `{% comment %}`.

any help would be appreciated.

**Comment by numToStr** [comment]
I hope you are using `gb` keybindings?

**Comment by farfanoide** [comment]
indeed, i've tested with a minimal vimrc:

```lua
require("packer").startup({
        function ()
                use("numToStr/Comment.nvim")
        end,
})

local comment_ft = require("Comment.ft")
comment_ft.set("htmldjango", { "{# %s #}", "{% comment %}%s{% endcomment %}" })
require("Comment").setup({})
```

Iput:
--
```htmldjango
[cursor here]{% extends "base.html" %}
{% load i18n %}
```

i press gbj and expected output is:

```htmldjango
{% comment %} {% extends "base.html" %}
{% load i18n %} {% endcomment %}
```
actual output:
--
```htmldjango
{ comment } {% extends "base.html" %}
{% load i18n %} {% endcomment %}
```

**Comment by numToStr** [comment]
Something must be going wrong with the commenstring parsing. I'll have a look.

**Comment by numToStr** [comment]
Should be fixed by https://github.com/numToStr/Comment.nvim/commit/538dac19fb982278613688627bef7c0d9c442748

**Comment by farfanoide** [comment]
working nicely, thanks for that!
