### ISSUE TITLE
Feat request: Add keymap descriptions

### ISSUE THREAD

**Issue by rafamadriz** [numToStr/Comment.nvim#189]
Giving a description to keymaps would integrate nicely with other plugins like for example `which-key.nvim`, other benefit is that you can know what exactly a keymap is for when using something like `verbose`.

With descriptions:
![Screenshot_20220731_152953](https://user-images.githubusercontent.com/67771985/182040399-d3376ae4-42ea-4ce0-bb79-cec82a829bdf.png)

Without descriptions:
![Screenshot_20220731_153241](https://user-images.githubusercontent.com/67771985/182040411-01d3c180-ddb0-47e5-8b79-d39b44a06a79.png)

As a reference, this was added to [kylechui/nvim-surround 
](https://github.com/kylechui/nvim-surround) in this commit https://github.com/kylechui/nvim-surround/commit/306a92830ede75d7d3a48ba04c7e603b73c3f377

**Comment by numToStr** [comment]
Sure. This will be a nice addition. PR also welcome :)

**Comment by rafamadriz** [comment]
Of course, I'd love to do a PR. Can I get some guidance ? If I understand correctly, I need to work on these two place:

https://github.com/numToStr/Comment.nvim/blob/2e0572cc35ecc117c0ab6dc0aa3132b109d61047/lua/Comment/api.lua#L238-L293

https://github.com/numToStr/Comment.nvim/blob/ef3e6bfa41073a73c298ae90d2796f8ceda71c6a/after/plugin/Comment.lua

**Comment by numToStr** [comment]
Yes, these 2 places should work.
