### ISSUE TITLE
Block comments are used instead of line comments

### ISSUE THREAD

**Issue by akdevservices** [numToStr/Comment.nvim#194]
Block comments are used instead of line comments when using Comment.nvim together with [nvim-treesitter-textobjects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects)

**Steps to reproduce**:
1. Use a plugin manager of your choice to install `nvim-treesitter-textobjects`. Configure `nvim-treesitter-textobjects`:
```
require'nvim-treesitter.configs'.setup {
    textobjects = {
        select = {
            enable = true,

            -- Automatically jump forward to textobj, similar to targets.vim
            lookahead = true,

            keymaps = {
                -- You can use the capture groups defined in textobjects.scm
                ["af"] = "@function.outer",
                ["if"] = "@function.inner",
            },
        },
    },
}
```
2. Make sure that Tresitter parser for C++ language is installed.
3. Create `test.cpp` file:
```
int main() {
    return 0;
}
```
4. Position cursor on `return 0` line.
5. Press `gcif`.

**Actual result** (`test.cpp`):
`/* return 0; */`

**Expected result** (`test.cpp`):
` // return 0;`

**Note**: Comment.nvim works as expected when function body has more than one line.

**Comment by numToStr** [comment]
Yes, this is expected and it is by design. So, When you do `gc[motion]` and if `motion` is done on a single line then block comments will be used. As this allows more single line motions like `gciw`, `gct,` `gcf)` etc to be work as expected. I hope this clears the confusion :)

**Comment by akdevservices** [comment]
I see. But it still feels wrong, whenever I want to use line comments and get block comments instead :) New plugin configuration settings could be introduced to explicitly specify that for particular mappings line comments shall be used.

**Comment by numToStr** [comment]
> New plugin configuration settings could be introduced to explicitly specify that for particular mappings line comments shall be used.

The plugin only defines only `gc` mapping and I am not sure how a configuration would solve this? Also considering every other character movement like `iw`, `t,` etc.

Besides that I am pretty sure that, in your case, pressing `gcif` would toggle the comment using block comment(?)
