### ISSUE TITLE
The `gcc` mapping only works in normal mode

### ISSUE THREAD

**Issue by refaelsh** [numToStr/Comment.nvim#195]
Hi,

The README states the following:
```lua
---LHS of toggle mappings in NORMAL + VISUAL mode
---@type table
toggler = {
        ---Line-comment toggle keymap
        line = 'gcc',
        ---Block-comment toggle keymap
        block = 'gbc',
    },
```

Well, for me, pressing `gcc` only works in Normal mode. In Visual mode it does not work.
Please help :-)

**Comment by numToStr** [comment]
That's a typo on the README. Would you mind creating a PR for it?

**Comment by refaelsh** [comment]
> That's a typo on the README. Would you mind creating a PR for it?

Oh, thank you for the answer. I will try and create a PR right now.

**Comment by refaelsh** [comment]
> That's a typo on the README. Would you mind creating a PR for it?

In the meantime, one a man to do for VISUAL mode? :-) What is the mapping instead of `gcc`?

**Comment by numToStr** [comment]
Just press `gc`

**Comment by refaelsh** [comment]
Well, then, in NORMAL mode I have `gcc` and in VISUAL mode I have `gc`?
Different mapping? It confuses the hell out of me.
How can I make this the same mapping in both modes?

**Comment by numToStr** [comment]
> It confuses the hell out of me.

That just idiomatic vim. Like for deletion, you pressing `dd` in normal mode and in Visual mode you select and press `d`.

You wanted to change just configure in setup.

**Comment by refaelsh** [comment]
> > It confuses the hell out of me.

> That just idiomatic vim. Like for deletion, you pressing `dd` in normal mode and in Visual mode you select and press `d`.

Interesting point.
 
> You wanted to change just configure in setup.

I tried it like this, but it only works in VISUAL mode.
```lua
     require('Comment').setup({
         toggler = {
             line = '<leader>c',
         },

         opleader = {
             line = '<leader>c',
         },
     })
```
Can you please suggest a way how I can make it the same mapping in both modes?


> Edit: To be clear I am not going to change any defaults.

I understand.

**Comment by numToStr** [comment]
Ohh I forgot to mention that, if you give `toggler` and `opleader` the same value then the mapping would conflict with each other.

**Comment by refaelsh** [comment]
> Ohh I forgot to mention that, if you give `toggler` and `opleader` the same value then the mapping would conflict with each other.

This is a bummer. So, it's impossible then to have the same mapping for commenting in both modes?

**Comment by numToStr** [comment]
You can't do much about the defaults mappings besides what's available but you can easily define your own using https://github.com/numToStr/Comment.nvim/blob/master/doc/plugs.md

**Comment by refaelsh** [comment]
> You can't do much about the defaults mappings besides what's available but you can easily define your own using https://github.com/numToStr/Comment.nvim/blob/master/doc/plugs.md

That worked. Thank you :-)
