### ISSUE TITLE
A question about `nvim-ts-context-commentstring`

### ISSUE THREAD

**Issue by refaelsh** [numToStr/Comment.nvim#196]
Hi,

I have a question please about this section in the README: https://github.com/numToStr/Comment.nvim#-treesitter.

Why is `nvim-ts-context-commentstring` not the default?

Thanks.

**Comment by numToStr** [comment]
What do you mean by default?

**Comment by refaelsh** [comment]
> What do you mean by default?

As far as I understand, in order to use the `nvim-ts-context-commentstring` feature, I need to configure something or other, right?
The question is, why wouldn't the plugin configure it itself and be done with it? Why bother the user with it?

**Comment by numToStr** [comment]
Why would a plugin include some glue code for another plugin that a user may or may not use? If you find `ts-context-commentstring` useful then what's the harm in adding 10 loc(?)

**Comment by refaelsh** [comment]
> Why would a plugin include some glue code for another plugin that a user may or may not use? If you find `ts-context-commentstring` useful then what's the harm in adding 10 loc(?)

1. Well, it looks to me that it's a very important feature that every user will want.
2. Adding 10 locs is not hard, but it's another thingy to keep track of when it is changes/updated/broken.

**Comment by numToStr** [comment]
1. I personally don't use `context-commentstring`. As `Comment.nvim` already has native support for embedded file types.

2. I can say the same thing ;)

**Comment by refaelsh** [comment]
> `Comment.nvim` already has native support for embedded file types.

Oh. Now I understand. Thank you for the answer.
