### ISSUE TITLE
dash brakets, --[[ comment ]]--, lua commenting

### ISSUE THREAD

**Issue by fdelacruz** [numToStr/Comment.nvim#201]
Hi, with the lastest update commenting a lua file yields dash brakets, --[[ comment ]]-- .
How do I switch back to just -- comment??

Thanks

**Comment by bryant-the-coder** [comment]
facing the same issue

**Comment by Blake-LeBlanc** [comment]
Same on my end as well

**Comment by numToStr** [comment]
In which key mapping you are facing this? Can you give me repro steps?

**Comment by bryant-the-coder** [comment]
gcc

**Comment by techtycho** [comment]
yup, I've tried `gcc`, which is intended for line-wise comments, along with some other keybindings; none of them worked

**Comment by numToStr** [comment]
I assuming you all are using `pre_hook`? Because it is working fine for me.

**Comment by LoganAtCrypto** [comment]
same issue here

**Comment by LoganAtCrypto** [comment]
resolved after removed the `nvim-ts-context-commentstring`.

**Comment by numToStr** [comment]
There is a breaking change with `U.ctype` utility which affected the `context-commenstring` integration (more details at #183). The snippet in README is already updated, you can copy paste the new snippet then everything should work as expected.

**Comment by fdelacruz** [comment]
It seems to be fixed with the latest updates.
Thanks

**Comment by bryant-the-coder** [comment]
how to fix? i still dont get it

**Comment by numToStr** [comment]
@bryant-the-coder https://github.com/numToStr/Comment.nvim/issues/201#issuecomment-1214163452

**Comment by fdelacruz** [comment]
In my case I updated my setup by replacing _line_ and _block_ with _linewise_ and _blockwise_ respectively.

**Comment by ethanmsl** [comment]
Hmm, that's surprising.
As a temporary fix I tried pinning both `numtostr/comment` and `J...A.../nvim-ts-context...` to previously working commits.  
Pinning JA/ts-context _did_ not change things, but pinning numtostr/comment _did_.

<img width="925" alt="pinned numtostr:comment" src="https://user-images.githubusercontent.com/33399972/184684569-400b12a6-7053-4ca9-a4e6-ce31dc89b327.png">


re:
```  
use { "numToStr/Comment.nvim", commit = "2c26a00f32b190390b664e56e32fd5347613b9e2" }
use { "JoosepAlviste/nvim-ts-context-commentstring", commit = "88343753dbe81c227a1c1fd2c8d764afb8d36269" }
```
referenced from : [chris@machine - basic-ide](https://github.com/LunarVim/nvim-basic-ide/blob/master/lua/user/plugins.lua)

**Comment by Raagh** [comment]
I am encountering the same but I am not using nvim-ts-context-commenstring.

lua require("Comment.api").toggle.linewise(vim.fn.visualmode())

comments correctly my typescript code with -- when it is a multi-line visual mode comment but fails to do so on single line visual mode. (single line non visual works fine)

**Comment by numToStr** [comment]
@Raagh I believe this is not related to this issue.

Anyway You need to first `<ESC>` from visual mode to make that API work. So, if you need custom keybindings, then I'll recommends you to use `<Plug>` mappings https://github.com/numToStr/Comment.nvim/blob/master/doc/plugs.md
