### ISSUE TITLE
API is broken

### ISSUE THREAD

**Issue by pedro757** [numToStr/Comment.nvim#215]
### Steps to reproduce
<details>
  <summary>Click me</summary>

1. `touch config.vim`
1. `nvim config.vim`
1. Paste this code in the `config.vim` file:
    ```vim
    if has('vim_starting')
      set encoding=utf-8
    endif
    scriptencoding utf-8

    if &compatible
      set nocompatible
    endif

    let s:plug_dir = expand('/tmp/plugged/vim-plug')
    if !filereadable(s:plug_dir .. '/plug.vim')
      execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
    end

    execute 'set runtimepath+=' . s:plug_dir
    call plug#begin(s:plug_dir)
      Plug 'numToStr/Comment.nvim'
    call plug#end()
    PlugInstall | quit

    " Setup global configuration. More on configuration below.
    lua << EOF
      require('Comment').setup()
    EOF
    ```
1. `nvim -u config.vim`
</details>

### Error 
**When trying to comment linewise:**
E117: Unknown function: v:lua.require'Comment.api'.locked'toggle.linewise.current'

**When trying to comment blockwise:**
E117: Unknown function: v:lua.require'Comment.api'.locked'toggle.blockwise'

**Comment by numToStr** [comment]
neovim version?

**Comment by pedro757** [comment]
NVIM v0.8.0-dev-896-g1a57cd383

**Comment by pedro757** [comment]
Nevermind I just updated neovim to the latest version, now it works, thank you!
