### ISSUE TITLE
Add the Ability to Insert a Comment in Insert Mode

### ISSUE THREAD

**Issue by amarakon** [numToStr/Comment.nvim#216]
I would like to add a keybinding that inserts a comment in insert mode. Here are some examples.

```
printf("Hello world\n")<c-c>My comment
```

```c
printf("Hello world\n") // My comment
```

```
int main(void)
{
    <c-c>My comment
}
```

```c
int main(void)
{
    // My comment
}
```

I achieved this by putting this in my Neovim configuration file:

```vim
imap <c-c> <cmd>s/\s\+$//e<return><cmd>noh<return><escape>gcA<space>
```

It first strips the trailing whitespace, then removes the highlighting with `noh`, then adds a comment at the end of the line. I think an option should exist in Comment.nvim so that I don't have to create this complicated command. Something that allows you to set a keybinding to comment in insert mode. I also think the default should be `<c-c>`.

**Comment by numToStr** [comment]
> I think an option should exist in Comment.nvim so that I don't have to create this complicated command

Sorry but no. And what's the problem with maintaining a keybinding?

> Something that allows you to set a keybinding to comment in insert mode. I also think the default should be <c-c>.

Again no, I won't be adding random keybindings to the plugin without any actual benefit.

**Comment by amarakon** [comment]
> Sorry but no. And what's the problem with maintaining a keybinding?

This type of behavior should be included by default in a comment plugin in my opinion because people don't just insert comments in normal mode.
And exiting insert mode just to insert a comment is not practical.
Everyone can add their own keybinding, but why would users have to make a complicated keybinding for something that is common?

> Again no, I won't be adding random keybindings to the plugin without any actual benefit.

You could instead create an option, and not have it set by default. That way, `<c-c>` will not be affected but people who want to insert comments in insert mode can set it to something like `<c-c>` using the option. It has the benefit of not having to exit insert mode to insert a comment or leaving it up to the user to create a complicated keybinding.

**Comment by amarakon** [comment]
Also, my keybinding isn't perfect because I have to exit insert mode to do it.

**Comment by numToStr** [comment]
Another way to add insert mode comment

```vim
imap <c-c> <c-o>gcc
```

---

Closing. I thought about this, and I am still not convinced about adding insert mode keybinds. As we already have lua API `:h comment.api` which can be used to create more complex bindings, if user wants.

**Comment by devkvlt** [comment]
@amarakon
```lua
vim.keymap.set('i', '<C-/>', require('Comment.api').toggle.linewise.current)
```
This does not exit insert mode.

**Comment by fidraC** [comment]
@devkvlt thank you. I was looking for that
