### ISSUE TITLE
[BUG] `api.uncomment.linewise.*` give error when nothing to uncomment

### ISSUE THREAD

**Issue by bew** [numToStr/Comment.nvim#221]
Plugin version: https://github.com/numToStr/Comment.nvim/commit/728f38ef5b9d77f310fc9d56f87582c24111f793

Using following config:
```lua
require('Comment').setup {
  mappings = {
    extended = true
  }
}
```

Given some file `foo.c`:
```
abc
```
With the cursor on the line, using `g<c` will give the following error:
```
E5108: Error executing lua Vim(lua):E5108: Error executing lua ...m-wip/managed-plugins/Comment.nvim/lua/Comment/utils.lua:65: attempt to get length of local 'iter' (a nil value)
stack traceback:
        ...m-wip/managed-plugins/Comment.nvim/lua/Comment/utils.lua:65: in function 'is_empty'
        ...m-wip/managed-plugins/Comment.nvim/lua/Comment/utils.lua:297: in function 'uncomment'
        ...-wip/managed-plugins/Comment.nvim/lua/Comment/opfunc.lua:176: in function 'linewise'
        ...-wip/managed-plugins/Comment.nvim/lua/Comment/opfunc.lua:68: in function 'opfunc'
        ...vim-wip/managed-plugins/Comment.nvim/lua/Comment/api.lua:284: in function 'current'
        [string ":lua"]:1: in main chunk
        [C]: at 0x004609a0
stack traceback:
        [C]: at 0x004609a0
```

**Comment by numToStr** [comment]
I would say that it's not a bug to uncomment a line which is not commented to begin with, but the panic makes it look like one.

**Comment by bew** [comment]
Yeah it's definitely useless, but can happen by mistake.. I think it should just do nothing

**Comment by numToStr** [comment]
To make this nicer I have to add checks in multiple places that's why left the panic as it is. But I'll think about it as I might also need to handle some other cases as well.

**Comment by winkee01** [comment]
I have encountered the same issue.

**Comment by numToStr** [comment]
FYI, extended keybindings are deprecated 20772ed7e9c70f55f0fc232f0cba5989cfb80727 but that is not an excuse to hide the underlying issue which is with API itself. I am going fix the panics sooner or later.

**Comment by bew** [comment]
Great, thanks 😀👍
