### ISSUE TITLE
[Feature] Allow `gcA` to be dot-repeated

### ISSUE THREAD

**Issue by bew** [numToStr/Comment.nvim#222]
Hello, when using `gcA` to add `// foo` to a line, moving to another line and hitting `.` adds `foo` but not the comment.

I think it would be nice UX to have dot-repeat work for this mapping :)

**Comment by numToStr** [comment]
I would doubt that this would work. Pressing `.` repeats the last change, which is `foo` in this case not `//`. I'd be a nice UX, yes, but not vim-ish.

**Comment by bew** [comment]
Well I don't agree, adding a comment at the end of the line looks like a single change to me, so it's still a vim-ish thing to me.

For example I can do (from normala mode): `A // foo<esc>` and that would do the same but manually. Thus I see `gcA` as a different way to go to the end of line start a comment, then I can write the comment.

**Comment by jjant** [comment]
👍 to @bew as well. The "change" here _is_ adding a `// foo` comment.

**Comment by numToStr** [comment]
> The "change" here is adding a // foo comment.

I am pretty sure inserting `// ` using `gcA` and typing `foo` amounts to 2 edits. OTOH this `A // foo<esc>` is a single edit.

**Comment by bew** [comment]
> I am pretty sure inserting `// ` using `gcA` and typing `foo` amounts to 2 edits. OTOH this `A // foo<esc>` is a single edit.

Yes, and this indeed explains the current behavior, that's why I raising this issue to see if that behavior can be changed.

Ideally I think that typing `gcA` would inject (based on the commentstring) the input `A // `, leaving me in insert mode so I can type my comment then press escape, the whole operation being a single change :)
