### ISSUE TITLE
[Feature request] Add `gcI` command

### ISSUE THREAD

**Issue by jjant** [numToStr/Comment.nvim#223]
Just like there's `gcA`, add `gcI` to comment the current line and put you in insert mode from the beginning:

```rust
let a = 42;
//      ^ cursor here
```
Press `gcI`

```rust
// let a = 42;
// ^ cursor here
```

**Comment by numToStr** [comment]
What's the actual use case for this? I can't think one for myself.

**Comment by jjant** [comment]
Many times I change code like
```rust
let a = 42;
```
To:
```rust
// TODO: Need to do X, Y, Z before enabling this
// let a = 42;
```

Which with `gcI` I could do with `gcITODO:...<CR>` thought admittedly this might be a strange way to go about doing that.

**Comment by numToStr** [comment]
You can simply do `nmap gcI gccgcO` this will work just fine for your use case.

**Comment by numToStr** [comment]
I am going to close this request as I don't see any actual use case for this.

**Comment by Freed-Wu** [comment]
As a completion, <https://github.com/tyru/caw.vim> provides `gcI` :smile:
