### ISSUE TITLE
wrong indent comment on empty line with tabs

### ISSUE THREAD

**Issue by shaeinst** [numToStr/Comment.nvim#225]
![image](https://user-images.githubusercontent.com/41078534/187042969-791b6d06-82d6-4fa4-aa73-d3000c4630a7.png)
when i multi select  the lines with empty line and `line-comment` then comment on empty line don't follows the indent. 
this happens with c/c++ file.

**Comment by numToStr** [comment]
Would you mind checking with other filetypes? If this issue exist or not.

**Comment by shaeinst** [comment]
working fine for python and javascript but lua has same issues as c and c++

**Comment by numToStr** [comment]
I tested it and can't reproduce the issue with both lua and cpp. would you mind writing down the actual steps?

**Comment by shaeinst** [comment]
i will try it with minimal config to know if any other plugins or my own config causing this.

**Comment by shaeinst** [comment]
ok i tested it with very possible minimal config, i don't think my any configs or plugins are causing this.

Neovim Version: v0.7.2
My Comment.nvim config:
```lua
-- safely import Comment
local comment_imported_ok, comment = pcall(require, 'Comment')
if not comment_imported_ok then return end

comment.setup({
	---Add a space b/w comment and the line
	---@type boolean
	padding = true,

	---Whether the cursor should stay at its position
	---NOTE: This only affects NORMAL mode mappings and doesn't work with dot-repeat
	---@type boolean
	sticky = true,

	---Lines to be ignored while comment/uncomment.
	---Could be a regex string or a function that returns a regex string.
	---Example: Use '^$' to ignore empty lines
	---@type string|function
	ignore = nil,

	---Pre-hook, called before commenting the line
	---@type function|nil
	-- NOTE: Already implemented with JoosepAlviste/nvim-ts-context-commentstring
	-- pre_hook = nil,

	---Post-hook, called after commenting is done
	---@type function|nil
	post_hook = nil,

	mappings = {
		basic = true, ---Includes `gcc`, `gcb`, `gc[count]{motion}` and `gb[count]{motion}`
		extra = true, ---Includes `gco`, `gcO`, `gcA`
		extended = false, ---Includes `g>`, `g<`, `g>[count]{motion}` and `g<[count]{motion}`
	},

	---LHS of toggle mapping in NORMAL
	---@type table
	toggler = {
		line = 'cc', ---line-comment keymap
		block = 'cb', ---block-comment keymap
	},

	---LHS of operator-pending mapping in VISUAL mode
	---@type table
	opleader = {
		line = 'gc', ---line-comment keymap
		block = 'gb', ---block-comment keymap
	},
})

```

**Comment by numToStr** [comment]
Still not able to reproduce. Can you write down the steps?

**Comment by shaeinst** [comment]
1. open file
2. select indented lines with empty lines
3. press gc
that's it.

**Comment by numToStr** [comment]
I believe tab indentation is the issue because I can't reproduce this anywhere else, except go files.

**Comment by shaeinst** [comment]
now this make sense. any file having tab indent has this issue. are you gonna fix this?

**Comment by numToStr** [comment]
This is unexpected behavior so yes. Otherwise there will be chaos in golang land XD.
