### ISSUE TITLE
[Feature Request] Use as a command.

### ISSUE THREAD

**Issue by singlexyz** [numToStr/Comment.nvim#226]
> You can also use it as a command, either with a range like :7,17Commentary, or as part of a :global invocation like with :g/TODO/Commentary. That's it.

Like this way:
<img width="493" alt="image" src="https://user-images.githubusercontent.com/4456413/187083518-0a862131-4d83-400b-a2e5-98df20f909b4.png">

**Comment by numToStr** [comment]
You can also use it like `:g/new/norm gcc`.

Coming to commands, i thought about it ages ago and decided to not implement it. What should I create commands for? linewise, blockwise. Someone might also want preview (inccommand), story goes on. I personally prefer to use keybindings for comments (and the example above), so the incentive is less for me. And if  you want, you can easily create that command using Lua api (`:h comment.api`)

**Comment by singlexyz** [comment]
> 

Ah yeah, this's a good way too.
