### ISSUE TITLE
[Bug] Error while trying to comment

### ISSUE THREAD

**Issue by Plucks77** [numToStr/Comment.nvim#227]
Hello, seems like commenting is broken for me:
![2022-08-30-092519_1485x734_scrot](https://user-images.githubusercontent.com/49085137/187436007-c2223845-8b6c-49da-b896-071bc15fee0c.png)

**Comment by numToStr** [comment]
You are using old API somewhere which is now deprecated #183

**Comment by Plucks77** [comment]
Totally my bad, thank you!
