### ISSUE TITLE
Marks disappear in un-/commented lines

### ISSUE THREAD

**Issue by astier** [numToStr/Comment.nvim#24]
If I set a mark at line `x` (ex. `mm` to set mark `m` at line `x`) and than un-/comment line `x` with `gcc` the mark gets deleted. This isn't an issue with vim-commentary.

**Comment by echasnovski** [comment]
The way I managed to solve this was [by using `lockmarks`](https://github.com/echasnovski/mini.nvim/blob/c03fc7d496aaa1de3c8d707cc30304b0acf2bcae/lua/mini/comment.lua#L124-L127). This needs some sort of exported function, but you seem to currently have it.

**Comment by numToStr** [comment]
> The way I managed to solve this was by using `lockmarks`

Hmmm, Interesting. I'll have a look. Thanks :)

**Comment by Grazfather** [comment]
I just noticed this issue as well. I had a mapping (with nerd commenter) that basically did:
1. Mark location
2. Append a TODO comment at EOL
3. Return to the original location.

This is broken with this plugin, unfortunately. Would be nice if you got this to work.

**Comment by numToStr** [comment]
Finally! The day has come #110

**Comment by Grazfather** [comment]
Works great!
