### ISSUE TITLE
Block line commenting is broken

### ISSUE THREAD

**Issue by mrjones2014** [numToStr/Comment.nvim#25]
Here's my config:

```
return {
  'numToStr/Comment.nvim',
  config = function()
    require('Comment').setup({
      mappings = {
        basic = false,
        extra = false,
      },
      toggler = {
        line = '<leader>c',
        block = '<leader>c',
      },
    })
  end,
}
```

And when I do `<leader>c` I get this error: `E5108: Error executing lua ...ite/pack/packer/start/Comment.nvim/lua/Comment/utils.lua:200: attempt to index local 'ln' (a nil value)`

**Comment by numToStr** [comment]
@mrjones2014 Try now. Also just so you know both `toggler.{line,block}` config need to have a different values.
