### ISSUE TITLE
feature: count prefixed mappings

### ISSUE THREAD

**Issue by thetic** [numToStr/Comment.nvim#26]
I think what makes this plugin so great is that the provided operators generally work as expected in vim (vertical and horizontal motions, etc). One missing piece of that though is count prefixed mappings. eg I would expect `5gcc`  to comment 5 lines.

See https://www.reddit.com/r/neovim/comments/q6lq5o/commentnvim_features_go_brrrrr/hgcxcok/

**Comment by numToStr** [comment]
I wasn't aware of this at the time of writing this plugin that most of the vim users are using the count prefix commenting. But I am certain that I'll implement this once I get the chance :)

**Comment by numToStr** [comment]
@thetic I was wondering, Would be the best for this `{count}gc` or `{count}gcc`? And I think dot repeat won't work with count prefixed mappings. Will this be ok?

**Comment by numToStr** [comment]
@thetic Wanna try #27

**Comment by thetic** [comment]
Looks good. Thanks so much!
