### ISSUE TITLE
util:155 expect string but got table

### ISSUE THREAD

**Issue by loenvom** [numToStr/Comment.nvim#263]
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/59039948/195817095-4c3c0d46-b85c-4edd-8349-c0079e1a9b13.png">
I think the problem may be the ft.get return table in some condition

**Comment by numToStr** [comment]
Reproduction steps?

**Comment by loenvom** [comment]
use nvim open a go file and try to comment one line then i get the error, but when i try to comment a js file it works

**Comment by numToStr** [comment]
Tested in go files using `gc` and `gcc`. No errors there.

**Comment by loenvom** [comment]
gcc does work, and i look through the config.basic, and i found the difference, when i try to comment with api `toggle.line` i get error, but when i try to comment with api `toggle.linewise` is works

**Comment by numToStr** [comment]
From where did you get the `toggle.line` API?

**Comment by loenvom** [comment]
<img width="567" alt="image" src="https://user-images.githubusercontent.com/59039948/195823224-c562b6ed-66b3-47cb-96d5-44db3562195a.png">
<img width="432" alt="image" src="https://user-images.githubusercontent.com/59039948/195823422-ce012cca-0656-4b85-9e7f-9f92f60a2820.png">
I try two api with lua command

**Comment by numToStr** [comment]
Please read the docs before using API.
