### ISSUE TITLE
Bug: E5108: Error executing lua when commenting kitty.conf

### ISSUE THREAD

**Issue by garymh** [numToStr/Comment.nvim#273]
Hi numToStr! I'm running into a small bug with commenting on kitty terminal config files. I'm trying to use `gcip` on a paragraph and I get:

```
E5108: Error executing lua Vim(lua):E5108: Error executing lua ...ite/pack/packer/start/Comment.nvim/lua/Comment/utils.lua:179: Vim:no parser for 'kitty' language, see :help treesitter-parsers
stack traceback:
        [C]: in function '__index'
        ...ite/pack/packer/start/Comment.nvim/lua/Comment/utils.lua:179: in function 'parse_cstr'
        ...te/pack/packer/start/Comment.nvim/lua/Comment/opfunc.lua:53: in function 'opfunc'
        .../site/pack/packer/start/Comment.nvim/lua/Comment/api.lua:43: in function 'linewise'
        [string ":lua"]:1: in main chunk
        [C]: at 0x010437c3a0
stack traceback:
        [C]: at 0x010437c3a0
```

I've looked through my config to see if I enabled some extra treesitter magic somewhere but couldn't seem to find anything. The line its pointing to suggests it might be a lack of `vim.bo.commentstring` but that shows as: 

```
:set commentstring
  commentstring=# %s
```
(which is correct)

The commenting still actually works correctly, but it just also throws this error message.

I'd be happy to send an nvim config if needed!

**Comment by numToStr** [comment]
I am pretty sure that I handled the missing treesitter parser here https://github.com/numToStr/Comment.nvim/blob/ad7ffa8ed2279f1c8a90212c7d3851f9b783a3d6/lua/Comment/ft.lua#L233

And I just checked and no error for me with `kittty` filetype using `gcip`.

**Comment by garymh** [comment]
> I am pretty sure that I handled the missing treesitter parser here

That does look like it would handle it! I just removed all of my plugins besides treesitter and Comment and it works - so it's something in my config! 

Thanks for the help!
