### ISSUE TITLE
packer.nvim Error running config for Comment.nvim: [string "....."] attempt to index a boolean value

### ISSUE THREAD

**Issue by hzd2020** [numToStr/Comment.nvim#274]
nvim 0.8.1 

packer.nvim Error running config for Comment.nvim: [string "....."] attempt to index a boolean value
![image](https://user-images.githubusercontent.com/65700504/202627368-681ef5d0-b38b-4cee-b92b-26a219d94cef.png)
![image](https://user-images.githubusercontent.com/65700504/202627431-ba825f80-36ce-4510-93c8-a24057905a22.png)

**Comment by numToStr** [comment]
Reproduction steps?

**Comment by hzd2020** [comment]
![image](https://user-images.githubusercontent.com/65700504/202637885-f4767f9d-bb65-4c4e-b9ab-95fbf57e029c.png)


open the nvim  
show me follow as :
![image](https://user-images.githubusercontent.com/65700504/202638024-6eeedd04-ed06-45ce-9ce3-5fa446d2fe12.png)

**Comment by hzd2020** [comment]
![image](https://user-images.githubusercontent.com/65700504/202638487-a82209b9-be54-400d-ae54-f7bb0d6a4d84.png)
this is my computer info

**Comment by numToStr** [comment]
Sorry, I am not getting that error.

**Comment by hzd2020** [comment]
Thank you very much. Is there a problem with my configuration file?

**Comment by numToStr** [comment]
All seems fine to me. If you are using nvim >= 0.8 then you can remove the `tag` and just use the latest master. If this doesn't fix it, then I am afraid IDK what's wrong with your setup.

Closing the issue now.
