### ISSUE TITLE
Use linewise instead of blockwise comments for languages that don't support block comments

### ISSUE THREAD

**Issue by emileferreira** [numToStr/Comment.nvim#275]
## Description

Languages such as Python and Bash don't support block comments. This results in undesirable behaviour when attempting to (un)comment blockwise using Comment.nvim; the linewise comment string is used as a fallback and inserted or removed at the start of the comment block, affecting only the first line of the block.

## Example

The following is Python code with the pipe representing the position of the Neovim cursor in normal mode.

```python
a = |1
b = 2
c = 3
```

If I were to press `gb2j`, the following would be observed.

```python
# a |= 1
b = 2
c = 3
```

While I would expect the following behaviour.

```python
# a |= 1
# b = 2
# c = 3
```

## Motivation

I'm aware that the workaround is to simply use linewise comment blocks in these files. However, I prefer to use blockwise comments for comment blocks and remembering to use a different keymap for these languages is avoidable mental overhead. I'm also quite certain that the current behaviour is not desired or expected by the majority of users.

**Comment by numToStr** [comment]
Closing because of https://github.com/numToStr/Comment.nvim/pull/276#issuecomment-1325430515
