### ISSUE TITLE
Add mappings to insert comment below/above/end of current line

### ISSUE THREAD

**Issue by astier** [numToStr/Comment.nvim#28]
## Problem

Sometimes I want to start writing a new comment above/below of current line. I do NOT mean un/commenting a line above/below the current line. I mean create a new empty line below/above the current line, insert commentstring at new line, enter insert mode after commentstring so I can immediately start writing the comment I want to write.

In the case of adding a new comment at the end of the current line I mean that the correct commentstring gets inserted at end of the current line and then the cursor gets moved to the end of the current line and put in insert mode.

## Reason

Comment.nvim is great because I can un/comment lines quick without thinking what is the correct commentstring for the particular language. Comment.nvim automatically chooses the correct commentstring for me. However, if I want to write a new comment I have to think about the commentstring and insert it myself. I want Comment.nvim to insert the correct commentstring for me if I want to write a new comment.

The only commenter-plugin I know of which can do that is https://github.com/tyru/caw.vim. This feature would certainly distinguish Comment.nvim from most other commenter-plugins.

## Solution

Add mappings:

- `gco` creates a new comment below the current line.
- `gcO` create a new comment above the current line.
- `gca` create a new comment at the end of the current line.

## Examples

Cursor position is `|`.

### `gco`

```
print("foo|")
```

type `gco`

```
print("foo")
// |
```

### `gcO`

```
print("foo|")
```

type `gcO`

```
// |
print("foo")
```

### `gca`

```
print("foo|")
```

type `gca`

```
print("foo") // |
```

**Comment by numToStr** [comment]
This is wonderful. Thanks for detailing the ideas @astier. Surely, INSERT mode mappings are missing and I do want to add them with also considering your suggestions.

One thing though, `gca` will conflict with other motions like `gcaw` `gcap` `gca{`

**Comment by astier** [comment]
Maybe than `gcA` would do it. Would be also consistent with `A` which puts the cursor in insert-mode at the end of the line.

**Comment by astier** [comment]
Hm. Not really. Do you have an example to illustrate what you have in mind?

**Comment by gegoune** [comment]
I like the idea of having an option to simply enable those keymaps. I would be using it.

I would suggest prefixing function names with `insert_`: `require('Comment').insert_comment_above()` might seem wordy, but `comment_above() suggest that function will comment existing line above cursor rather than insert new line with comment marker.

**Comment by numToStr** [comment]
Hey @astier @gegoune, Wanna try #31? 😄
