### ISSUE TITLE
Broken lua comments if the commented line/block contains closing brackets

### ISSUE THREAD

**Issue by llyyr** [numToStr/Comment.nvim#280]
Current behavior

`vim.cmd[[colorscheme test]]` -> `--[[ vim.cmd[[colorscheme test]] ]]`

Expected behavior

`vim.cmd[[colorscheme test]]` -> `--[[ vim.cmd[[colorscheme test\]\] ]]`

**Comment by piersolenski** [comment]
Same issue 😩

**Comment by numToStr** [comment]
It could become complicated to support this is kind of scenarios, if we factor in other languages. I know this is frustrating, but you could always linewise comments to cover up this scenario.

Closing this for now.
