### ISSUE TITLE
[Question] How can I use the line-comment symbol when triggering a blockquote

### ISSUE THREAD

**Issue by LukasPietzschmann** [numToStr/Comment.nvim#286]
I'm writing a lot of documents in TeX, which does no support block comments. But I regularly catch myself selecting a block of text and then triggering a block comment, resulting in only the first line to be commented.
Is it possible to change this behavior. I'd find it pretty useful if the plugin could just paste the line comment character before every line if no block comments are available.

**Comment by numToStr** [comment]
> and then triggering a block comment

What's the issue with selecting lines and pressing `gc`?

**Comment by LukasPietzschmann** [comment]
Omg I'm kinda embarrassed that I didn't came up with that myself.
That's obviously a great solution.
Sorry for bothering you ':)
