### ISSUE TITLE
Help: how to comment lua code in vimscript?

### ISSUE THREAD

**Issue by krisfans** [numToStr/Comment.nvim#287]
for example ,there is  a piece of code in my vimrc, what should I do to comment `bar1` with Comment.nvim?
```vim
foo
lua << EOF
bar1
bar2
EOF
```
I hnow [caw.vim](https://github.com/tyru/caw.vim) together with  [context_filetype.vim](https://github.com/Shougo/context_filetype.vim) can deal with this situation, may be helpful.
Thanks.

**Comment by numToStr** [comment]
Please use discussion for questions.
