### ISSUE TITLE
Commenter not working

### ISSUE THREAD

**Issue by rcclemente** [numToStr/Comment.nvim#290]
Hi,

I have recently migrated to using full lua with my nvim. In my previous vimscript i was using https://github.com/tpope/vim-commentary

I added this to my plugins.lua 

```
  use {
      'numToStr/Comment.nvim',
      config = function()
          require('Comment').setup()
      end
  }
 ```
Installed and restarted

tried the command gcc, gc11j ... etc

Is there a way to debug this? 

Regards

**Comment by numToStr** [comment]
Try https://github.com/numToStr/Comment.nvim/issues/115#issuecomment-1032290098

**Comment by rcclemente** [comment]
@numToStr thanks but i found an issue from my default config. It is working great now
