### ISSUE TITLE
support .editorconfig

### ISSUE THREAD

**Issue by matu3ba** [numToStr/Comment.nvim#292]
see https://editorconfig.org/:
```
Only forward slashes (/, not backslashes) are used as path separators and octothorpes (#) or semicolons (;) 
are used for comments. Comments should go on their own lines.
```

Comments are prefixed with `#`

For the neovim helpage: `:h editorconfig`.

**Comment by numToStr** [comment]
PR?

**Comment by matu3ba** [comment]
I am not familiar with the in-documentation language highlighting or if you use it at all, but this would make things faster (probably also adding it into the README):
```
diff --git a/lua/Comment/ft.lua b/lua/Comment/ft.lua
index d5e4daf..4fab693 100644
--- a/lua/Comment/ft.lua
+++ b/lua/Comment/ft.lua
@@ -8,6 +8,9 @@
 ---'ios.swift' etc. The commentstring resolution will be done from left to right.
 ---For example, If the filetype is 'ansible.yaml' then 'ansible' commenstring will
 ---be used if found otherwise it'll fallback to 'yaml'. Read `:h 'filetype'`
+---or try locally in an opened file within vim cmdline:
+---:lua print(vim.bo.filetype)
+---:lua print(require("nvim-treesitter.parsers").filetype_to_parsername[vim.bo.filetype])
 ---@brief ]]
```

**Comment by numToStr** [comment]
> I am not familiar with the in-documentation language highlighting or if you use it at all, but this would make things faster (probably also adding it into the README):
> ```diff
> diff --git a/lua/Comment/ft.lua b/lua/Comment/ft.lua
> index d5e4daf..4fab693 100644
> --- a/lua/Comment/ft.lua
> +++ b/lua/Comment/ft.lua
> @@ -8,6 +8,9 @@
>  ---'ios.swift' etc. The commentstring resolution will be done from left to right.
>  ---For example, If the filetype is 'ansible.yaml' then 'ansible' commenstring will
>  ---be used if found otherwise it'll fallback to 'yaml'. Read `:h 'filetype'`
> +---or try locally in an opened file within vim cmdline:
> +---:lua print(vim.bo.filetype)
> +---:lua print(require("nvim-treesitter.parsers").filetype_to_parsername[vim.bo.filetype])
>  ---@brief ]]
> ```

Huh? What's the point here? I thought you wanted to add to add support for editorconfig files(?)

**Comment by matu3ba** [comment]
Point being is that getting treesitter used filetype is not documented in `:h filetype`.
