### ISSUE TITLE
`require('Comment').toggle()` from visual mode only comments top line

### ISSUE THREAD

**Issue by mrjones2014** [numToStr/Comment.nvim#30]
I've bound a key bind to `:lua require('Comment').toggle()<CR>`

![CleanShot-2021-10-14-at-19 59 06](https://user-images.githubusercontent.com/8648891/137411220-6a1fb743-3b43-4ce5-82f4-f422a2fce962.gif)

**Comment by mrjones2014** [comment]
(If I want to keep all my keymaps in the same place and not set them through Comment.nvim config)

**Comment by blackflame007** [comment]
@mrjones2014 This should help https://github.com/numToStr/Comment.nvim/blob/2f19303c0641537e63a2c44f754c41f7a122e6d7/lua/Comment/api.lua

Here is what I did `vnoremap <leader>/ :lua require('Comment.api').gc(vim.fn.visualmode())<CR>', { noremap = true, silent = true })<CR>`
