### ISSUE TITLE
`gv` fails after toggling a linewise comment

### ISSUE THREAD

**Issue by hinell** [numToStr/Comment.nvim#302]
https://user-images.githubusercontent.com/8136158/215853787-f687ce4c-eaba-41b2-b7de-323b2831ff2b.mp4

Ordinary <kbd>Shift+v</kbd> <kbd>gcc</kbd> toggles linewise comment, and then <kbd>gv</kbd> selects the latest selection again.

BUT with the following config <kbd>gv</kbd> typed after <kbd>&lt;CUSTOM-SHORTCUT></kbd>sequence fails to select the same two lines:

```lua
vim.keymap.set("v", "<CUSTOM-SHORTCUT>", function()
	local esc = vim.api.nvim_replace_termcodes(
		'<ESC>', true, false, true
	)
	local comment = require("Comment.api")
	vim.api.nvim_feedkeys(esc, 'nx', false)
	comment.toggle.linewise(vim.fn.visualmode())
end)
```

Binding <kbd>&lt;CUSTOM-SHORTCUT> to `gc` doesn't work as well.

**Comment by hinell** [comment]
I would prefer not to loose the focus on the last selection that got commented.
Would be best if I could tweak this behavior via `comment.toggle.linewise(...)` option.

**Comment by RazaGR** [comment]
is there solution for it?

**Comment by hinell** [comment]
There is none so far.

**Comment by numToStr** [comment]
This is already discussed in https://github.com/numToStr/Comment.nvim/discussions/299

**Comment by RazaGR** [comment]
Thanks @numToStr , any idea why it's not working? I have to manually press gv to highlight again

```
return {
  {
    "numToStr/Comment.nvim",
    dependencies = { "JoosepAlviste/nvim-ts-context-commentstring" },
    opts = function()
      local U = require("Comment.utils")
      return {
        pre_hook = require("ts_context_commentstring.integrations.comment_nvim").create_pre_hook(),
        post_hook = function(ctx)
          -- Check whether we were in VISUAL mode
          if ctx.cmotion == U.cmotion.v or ctx.cmotion == U.cmotion.V then
            vim.cmd("norm! gv")
          end
        end,
      }
    end,
  },
}
```

**Comment by RazaGR** [comment]
my bad, It works, Thanks
