### ISSUE TITLE
Need help for vimwiki with markdown syntax

### ISSUE THREAD

**Issue by G0V1NDS** [numToStr/Comment.nvim#308]
I am using vimwiki with `markdown` syntax.
Have added below line in `ftplugin->vimwiki.vim` to override default commentstring(`%%`) for vimwiki:
```vim
set commentstring=<!--\ %s\ -->
```

This works well and gcc adds proper comment like this:
```markdown
<!-- TODOs -->
```
But for code blocks also it uses the same commentstring, while in markdown file it works well.

My understanding is, this plugin determines the commentstring with help of tree-sitter so I even tried setting the `markdown` parser for `vimwiki` file, and now the vimwiki files are using `markdown` syntax but it didn't help.

<br>

Snippet used for overriding the `vimwiki` tree-sitter parser:
```lua
local ft_to_parser = require"nvim-treesitter.parsers".filetype_to_parsername
ft_to_parser.vimwiki = "markdown"
```

**Note:** Filetype for vimwiki files is `vimwiki` only, I don't want to change that, because if I change that I'll loose the mapping and functionalities defined by vimwiki pluggin.

**Comment by numToStr** [comment]
Please use [discussions](https://github.com/numToStr/Comment.nvim/discussions) for asking questions.
