### ISSUE TITLE
Break very hard on Lua `vim.cmd(simple_str)`.

### ISSUE THREAD

**Issue by nyngwang** [numToStr/Comment.nvim#311]
If it's `vim.cmd('simple string')` it breaks. If there are some Lua concatenation via `..` then no error. See:

https://user-images.githubusercontent.com/24765272/221481149-ec76efe5-5cf1-46df-92fd-dba819314dc9.mov

**Comment by numToStr** [comment]
This is a known limitation where a single line contains multiple languages, in this case it's vimscript and lua. Please read https://github.com/numToStr/Comment.nvim/issues/144
