### ISSUE TITLE
Uncomment code block even if an uncommented line is present

### ISSUE THREAD

**Issue by backdround** [numToStr/Comment.nvim#312]
I'm often tries to uncomment something like this by `uncomment mapping` + motion `}`:
```lua
  |
  -- options.timeout = false
  -- options.scrolloff = 10
  -- options.mouse = "a"
  -- options.swapfile = false
end

```

but mapping `api.call("uncomment.linewise", "g@")` doesn't work for that case.

It doesn't work with this too (common for me):
```lua
|
-- options.timeout = false
-- options.scrolloff = 10
options.mouse = "a"
-- options.swapfile = false

```

Is there a way to do so? thanks in advance

**Comment by numToStr** [comment]
I am not sure what you are asking and please use discussions for asking questions.
