### ISSUE TITLE
Powershell `ps1` filetype not working

### ISSUE THREAD

**Issue by jeeeem** [numToStr/Comment.nvim#317]
![image](https://user-images.githubusercontent.com/51053482/226209116-36889b47-2b51-421f-9ce4-a01dc5807937.png)

Although it already has a set commentstring to #%s
![image](https://user-images.githubusercontent.com/51053482/226209205-77dfbd3f-8dd8-4ac0-ab8a-d9d178f96002.png)

**Comment by numToStr** [comment]
It is fixed now. Please use master.

![image](https://user-images.githubusercontent.com/24727447/235069759-2be136b5-5c9b-41a7-9b12-8e6fa0e3177c.png)
