### ISSUE TITLE
feature request: balancing comment lines

### ISSUE THREAD

**Issue by sevensidedmarble** [numToStr/Comment.nvim#321]
Hi,

There's one feature out there that I haven't seen any other comment plugin do. When you have your line length set to a certain length, say 120 or 80 or whatever, and you start typing a comment that breaks onto the next line, sometimes you get really weird comment blocks where the first line is really long and the second is only a couple words.

Sometimes I go in manually and 'rebalance' the lines by eye, which makes them look a lot better, but it a lot of work. It'd be fantastic to have a commenting plugin that just knew to do this automatically, or at least had a command to do it.

**Comment by numToStr** [comment]
I also noticed this myself but don't know the solution, must be some setting, IDK. But This has nothing to do with the commenting plugin. So, closing this for now.
