### ISSUE TITLE
[Feature Request] Support multiple line comment styles

### ISSUE THREAD

**Issue by thisisrandy** [numToStr/Comment.nvim#322]
Some languages, e.g. rust (`///`) and haskell (`-- |`) have special line comment styles for docstrings and perhaps other purposes that I'm unaware of. As `Comment.nvim` only supports one expression for each of line and block comments, the remainder of the docstring preamble is left in place (for rust, `/\s*`, and for haskell, `|\s*`). It would be really neat if uncommenting lines styled with the docstring format would remove the entire comment preamble and trim leading spaces the way it does for normal line comments. I imagine this would involve a hierarchy: using rust as an example, check first for `///%s` and then `//%s`. Obviously there's no way to know when commenting lines which style to use without user input, so either ignore the issue and always use some notion of a default style or provide bindings to select the intended style.

I'll note that it may be possible to do the uncommenting portion somewhat hackishly with a `post_hook`, e.g. by deleting all leading forward slashes and spaces in uncomment mode in the rust example, but a specific feature for multiple comment styles would probably be much cleaner.

**Comment by numToStr** [comment]
> I imagine this would involve a hierarchy

You can't say for sure that you can go with the same "hierarchy" approach for every language.

Adding support for doc comments in the plugin would require some thinking. But if you want to implement this by yourself, you can use `:h comment.utils` functions (more specifically by combining `comment.utils.{unwrap_cstr,commenter,uncommenter}`).

That being said, I am going to close for now as I don't think I'll be able to add this into the plugin soon.

**Comment by thisisrandy** [comment]
Okay, thanks for the tip. No promises, but I'll take a look at what you've suggested. Would appreciate an open feedback line on this issue if I have any questions.
