### ISSUE TITLE
Last update broke commenting on csharp filetype.

### ISSUE THREAD

**Issue by DannyDevLazy** [numToStr/Comment.nvim#328]
Hi, firstly let me say thanks for your work on this plugin. It is a must have in my config.
Now for my problem. After the last update when working on csharp file i had this error.
`[Comment.nvim] Invalid commentstring for cs! Read `:h commentstring` for help.`

After looking at source code I saw that you removed passing of the filetype to the `vim.treesitter.get_parser` and you are only passing a buffer to it. After I added it back in it worked as it used to.

**Comment by numToStr** [comment]
Are you on nvim 0.9?

**Comment by DannyDevLazy** [comment]
I use neovim nightly.
Version: NVIM v0.10.0-dev-42+g880f7d12f

**Comment by numToStr** [comment]
Hmmm.... Maybe treesitter is returning `csharp` for this filetype.

Can you try running the following

```lua
local ft = require'Comment.ft'

ft.set('csharp', ft.get('cs'))
```

**Comment by DannyDevLazy** [comment]
I tried but it still gives the same message.

**Comment by numToStr** [comment]
After some debugging, it seems the parser name is `c_sharp`. So, the following should work

```lua
local ft = require'Comment.ft'

ft.set('c_sharp', ft.get('cs'))
```

**Comment by numToStr** [comment]
Also, `cs` files doesn't have `commentstring` set by default which is the main issue here.

**Comment by numToStr** [comment]
> When you raise the required Neovim version to 0.9, you can use vim.treesitter.language.get_filetypes() together with vim.filetype.get_option() to get the effective commentstring, including from plugin- or user-set values.

Yes, I was following these but lost track mid way. Anyway I'll try to use those APIs and see whether they bring any improvements over the current implementation.

**Comment by clason** [comment]
The improvement would be to avoid having to maintain your own parser -> commentstring mappings.
