### ISSUE TITLE
Python comments are broken

### ISSUE THREAD

**Issue by eelkeh** [numToStr/Comment.nvim#329]
Previously it would comment out lines and blocks with a prepended hash `#`, now every line is treated as a docstring with `""""` I'm not sure in what commit this broke but I suspect it's a fairly recent change. 

Expected behaviour (`filetype=python`)
```python
a = 1
# a = 1
```
Actual behaviour:
```python
a = 1
""" a = 1 """
```

**Comment by numToStr** [comment]
Working just fine for me. Make sure you are on 0.9 stable.

**Comment by crzdg** [comment]
Yes seems to be related to `nvim-ts-context-commentstring` and its configuration breaking some things. Had to disable it as well to get the `Comment` to work as expected.
