### ISSUE TITLE
Incorrect documentation about `post_hook`

### ISSUE THREAD

**Issue by ray-x** [numToStr/Comment.nvim#33]
I am trying post_hook

```lua
post_hook = function(ctx, start_col, end_col, start_row, end_row)
    print(start_row, end_row, start_col, end_col)
end
```
From the print result, it looks to me the function prototype should be
```lua
post_hook = function(ctx, start_row, end_row, start_col, end_col, )
    print(start_row, end_row, start_col, end_col)
end
```
Is there something wrong?

**Comment by numToStr** [comment]
@ray-x I've added `V` as a Comment motion in 4d8590e. So you can work around this issue if you want.

Previous `cmotion` was `0`
```lua
{
    cmode = 1,
    cmotion = 0,
    ctype = 1,
}
```
Now it will be this
```lua
{
    cmode = 1,
    cmotion = 5,
    ctype = 1,
}
```
---
I am closing this as this is not an issue within this plugin :)

**Comment by numToStr** [comment]
Ohhh, Now I feel stupid 😅. I mixed up row and col with each other and this is inside the whole codebase 😰.

**Comment by numToStr** [comment]
@ray-x Thanks a ton. I'll fix this as soon as I am on my desk again.
