### ISSUE TITLE
Vue comments are broken

### ISSUE THREAD

**Issue by YTheSeven** [numToStr/Comment.nvim#330]
The submission from a month ago still seems to be correct

Expected behaviour (filetype=vue)
```
<style>
/* display: flex; */
</style>
```
Actual behaviour:

```
<style>
<!-- display: flex;  -->
</style>
```

**Comment by numToStr** [comment]
Please provide proper steps.

**Comment by YTheSeven** [comment]
> Please provide proper steps.

It was working fine before, after I did an update this problem occurs

**Comment by numToStr** [comment]
Working just fine for me. Make sure you are on 0.9 stable.

**Comment by YTheSeven** [comment]
> Working just fine for me. Make sure you are on 0.9 stable and vue treesitter parser installed.

on commit ab62084fa992ed7ee3c19bbb5227ce2c4234612b,it's ok

**Comment by numToStr** [comment]
If you are using 0.8, then you can stick to that commit. I am on nvim 0.9 and everything is working fine for me.

**Comment by YTheSeven** [comment]
I also using 0.9
```
NVIM v0.9.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Comment by numToStr** [comment]
It seems you are a nightly user. Would you mind updating to the latest nightly?

**Comment by YTheSeven** [comment]
> It seems you are a nightly user. Would you mind updating to the latest nightly?

OK,i will try,thank you so much😊

**Comment by YTheSeven** [comment]
Now it works!
```
<style>
/* display: flex; */
</style>
```
but use scss work bad
```
<style lang="scss" scoped>
<!-- display: flex;  -->
</style>
```

**Comment by numToStr** [comment]
Do you have scss parser installed?

**Comment by YTheSeven** [comment]
> Do you have scss parser installed?

i install nvim-ts-context-commentstring and it worked fine,thanks!🎉🎉🎉

**Comment by valyntyler** [comment]
I'm also having this issue. This fix doesn't seem to work

> > Do you have scss parser installed?
> 
> i install nvim-ts-context-commentstring and it worked fine,thanks!🎉🎉🎉

**Comment by YTheSeven** [comment]
> I'm also having this issue. This fix doesn't seem to work
> 
> > > Do you have scss parser installed?
> > 
> > 
> > i install nvim-ts-context-commentstring and it worked fine,thanks!🎉🎉🎉

I recently reinstalled my system and encountered the same problem, but I haven't been able to resolve it yet.
