### ISSUE TITLE
Proto filetype is not working

### ISSUE THREAD

**Issue by bamzi** [numToStr/Comment.nvim#333]
When toggling comment for `.proto` Protobuf files, the following message is shown:
`[Comment.nvim] Invalid commentstring for {filetype}! ....`

Please add support for proto files.
Proto files support both `//` style for line by line commenting as well as `/* .... */` style for multi-line block commenting

**Comment by bamzi** [comment]
Closing this. Should have read the documentation. Though it would've been nice to have native support for proto files.

Solution:
```
local ft = require('Comment.ft')
ft.set('proto', {'//%s', '/*%s*/'})
```

**Comment by numToStr** [comment]
PR is welcome :)
