### ISSUE TITLE
[Question] Key mapping with Comment shortcut

### ISSUE THREAD

**Issue by liketoeatcheese** [numToStr/Comment.nvim#335]
Hey mate,

First of all, awesome work on the plugin!

To my question, to comment on the whole paragraph, I normally have to `vip` to select the whole paragraph and then `gc` to toggle the comment. I want to shorten this by creating a keymap with `gcp`:
`keymap("n", "gcp", "vipgc", opts)`

But when I do that, it only selects the paragraph without commenting it, is there a way to call that as a lua function? Something like this: 
`keymap("n", "gcp", "vip:CommentToggle", opts)`

I hope that makes sense

**Comment by numToStr** [comment]
Please use Discussions to ask your question.
