### ISSUE TITLE
custom key maps with <leader> not work

### ISSUE THREAD

**Issue by dc3671** [numToStr/Comment.nvim#337]
My `<leader>` is `,`. However if I setup custom key maps according to Readme:
```
---require('Comment').setup({
---    ignore = '^$',
---    toggler = {
---        line = '<leader>cc',
---        block = '<leader>bc',
---    },
---    opleader = {
---        line = '<leader>c',
---        block = '<leader>b',
---    },
---})
```
The actual map is:
![image](https://user-images.githubusercontent.com/5948851/233815886-0ff25eec-4968-4c34-bd7f-d5261c8c07b8.png)

**Comment by Sonicfury** [comment]
Same here, `<leader>` key remaps don't work for me either !

**Comment by dc3671** [comment]
Actually I fixed this problem on my configs now. I figured out that it's caused by the order of setting your `leader` key.
If I set it before Comment's setup, it will work.

But it's still a problem of Comment's key mapping. Maybe it's using hardcode string way rather than variable way?

**Comment by numToStr** [comment]
> If I set it before Comment's setup, it will work.

Obviously, you need to set it before using the updated value.

> Maybe it's using hardcode string way rather than variable way?

How so? 

---

There is nothing special going on keymaps you can read the following code https://github.com/numToStr/Comment.nvim/blob/a89339ffbee677ab0521a483b6dac7e2e67c907e/lua/Comment/init.lua#L98-L131. I don't think this is a issue with the plugin, so closing this for now.

**Comment by Sonicfury** [comment]
Yep, I deleted the plugin, and put it back (packer) everything seems to be working fine now. 
Maybe I did a typo the first times, idk.
