### ISSUE TITLE
astro comments not working "invalid comment string"

### ISSUE THREAD

**Issue by tjex** [numToStr/Comment.nvim#347]
[astro](www.astro.build) has a [treesitter parser](https://github.com/virchau13/tree-sitter-astro), but it seems Comment and treesitter aren't fully playing together out of the box. Wanted to check in here before going down the JoosepAlviste/nvim-ts-context-commentstring route. 

Commenting in the typescript 'header' part of a `.astro` file works. 

eg: 
```
---
typescript -> here it works
---
<html> -> here does not
```

In the `html` section, attempting to comment returns the error:
```
[Comment.nvim] Invalid commentstring for astro! Read `:h commentstring` for help.
```

Should they be working by default (as per the readme statement -> if treesitter parser, then it works)? 
Or is astro an edge case as it's a relatively new format?

**Comment by numToStr** [comment]
Try to check the parsed tree (using Playground) and the language you are getting at the `<html>` node, I guess there must be something funny going on.

**Comment by tjex** [comment]
Yup. The html is defined as `astro` for its language. 
Adding this to my config works. 

```lua
require('Comment').setup()

local ft = require('Comment.ft')
ft.set('astro', '<!--%s-->')
```

thanks. I will make a PR for this.
