### ISSUE TITLE
Racket's comment differs from other Lisps

### ISSUE THREAD

**Issue by oyarsa** [numToStr/Comment.nvim#355]
I've tested Clojure (`.clj`), Common Lisp (`.lisp`), Scheme (`.scm`) and Racket (`.rkt`), and all except Racket and Fennel are commented `;;`:

```clojure
;; (atom? 'atom)
```

Racket gets commented with the multi-line form, even for a single line:

```racket
#| (atom? 'atom) |#
```

Fennel is commented with a single semicolon:

```fennel
; (atom? 'atom)
```

Why is that? Can it be changed? It should be the same as the other lisps.

**Comment by numToStr** [comment]
I am no lisp guy, so can't say what is wrong or right. If you think the current behavior is wrong, then a PR to fix this would be very welcome.

**Comment by oyarsa** [comment]
I'm pretty sure `;;` is right for Racket as it is for the rest, but I took a look at the code and couldn't understand why it is different. As far as I can see, there's a single definition for all lisps, so I don't know why Racket isn't doing the same as the rest. Fennel using `;` instead of `;;` is also weird.

Can you point me in the general direction? I'd love to open a PR to fix this.

**Comment by oyarsa** [comment]
Right. I'll take another look and open a PR. Thanks!
