### ISSUE TITLE
Default configuration contains keymap conflicts

### ISSUE THREAD

**Issue by k84d** [numToStr/Comment.nvim#364]
## Configuration contains keymap conflicts

The ':checkhealth' output contains the following WARNINGs:

```
which-key: require("which-key.health").check()

WhichKey: checking conflicting keymaps ~
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"gb"**
- rhs: `<Plug>(comment_toggle_blockwise)`
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"gc"**
- rhs: `<Plug>(comment_toggle_linewise)`
```

## To Reproduce

1. :checkhealth

## Desktop

- OS: MacOS 13.3.1a
- Terminal: iTerm2 3.4.19

## Neovim Version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.1/share/nvim"
```
```

**Comment by numToStr** [comment]
Please find out the conflicting keymaps in your config. It's not the issue in the plugin.

**Comment by DianQK** [comment]
> Please find out the conflicting keymaps in your config. It's not the issue in the plugin.

I can verify that this conflict occurs in https://github.com/numToStr/Comment.nvim/blob/0236521ea582747b58869cb72f70ccfa967d2e89/lua/Comment/init.lua#L100-L110.

If I understand the following code correctly, `gc` and `gcc` conflict with each other.
```lua
 K('n', 'gc', '<Plug>(comment_toggle_linewise)', { desc = 'Comment toggle linewise' })
 K('n', 'gcc', function() 
     return vvar('count') == 0 and '<Plug>(comment_toggle_linewise_current)' 
         or '<Plug>(comment_toggle_linewise_count)' 
 end, { expr = true, desc = 'Comment toggle current line' }) 
```

This is why we need to set the `timeoutlen` in the https://github.com/numToStr/Comment.nvim/issues/115#issuecomment-1032290098.

**Comment by cxwx** [comment]
still not fixed
