### ISSUE TITLE
Issue with HCL files

### ISSUE THREAD

**Issue by krzkrzkrz** [numToStr/Comment.nvim#382]
I get the following when trying to comment a line in an `.hcl` file:

```
[Comment.nvim] Invalid commentstring for hcl! Read `:h commentstring` for help.
```

**Comment by favadi** [comment]
I created a PR for it: https://github.com/numToStr/Comment.nvim/pull/398, in the mean time, you manually configure the comment strings for .hcl files by:

```lua
      local ft = require('Comment.ft')
      ft.hcl = { '#%s', '/*%s*/' }

      require('Comment').setup()

```
