### ISSUE TITLE
how to add a header comment?

### ISSUE THREAD

**Issue by tiansira** [numToStr/Comment.nvim#392]
does anyone know how to add a header comment?

**Comment by bew** [comment]
What do you mean by 'header comment' ? Could you give examples?

**Comment by tiansira** [comment]
like this. at the beginning of the file, one-click to add a header comment.
###
 # @Author: xxx
 # @Date: xxx
 # @LastEditTime: xxx
 # @Description: 
###

**Comment by numToStr** [comment]
Please move this to discussions.
