### ISSUE TITLE
NOT A BUG/ISSUE [a gen qs]

### ISSUE THREAD

**Issue by daUnknownCoder** [numToStr/Comment.nvim#408]
hey bud, the gif u hav in ur readme, what is that? like in the lualine, in the 'X' column, u have a 🦊 lua which changes what is that?
thanks for the answer anyway...

**Comment by decipher-cs** [comment]
It's better to ask questions in the [discussion](https://github.com/numToStr/Comment.nvim/discussions) section rather then creating a new issue.  Although, your question belongs in the [lualine](https://github.com/nvim-lualine/lualine.nvim/discussions) repo to begin with.

As for how that emoji is setup? It's seems to me it's just using the "symbol" key in the config to setup emoji based on file/ buffer type. Similar to this:
```lua
ins_right {
        'diff',
        symbols = { added = ' ', modified = '柳 ', removed = ' ' },
        diff_color = {
                added = { fg = colors.green },
                modified = { fg = colors.orange },
                removed = { fg = colors.red },
        },
        cond = conditions.hide_in_width,
}
```

**Comment by daUnknownCoder** [comment]
ah sorry for coming here thats why i added a disclaimer in my issue title...
