### ISSUE TITLE
Adding a FOSS license

### ISSUE THREAD

**Issue by ColinKennedy** [numToStr/Comment.nvim#428]
Hi, I love and use this plug-in every day. It makes using Vim so much better! My workplace is cautious about allowing code without a `LICENSE` file and it'd be a big help if this plug-in could use a FOSS license. I'm sure others in the same position and would appreciate it too. Could a FOSS license please be added if this plug-in is meant for public use? Ideally [as a new release](https://github.com/numToStr/Comment.nvim/releases). Thank you very much!

**Comment by flexagoon** [comment]
This project literally has a license file though?

https://github.com/numToStr/Comment.nvim/blob/master/LICENSE

**Comment by ColinKennedy** [comment]
My bad, thank you for pointing this out!
