### ISSUE TITLE
Not working for typescript react 

### ISSUE THREAD

**Issue by khanakia** [numToStr/Comment.nvim#429]
When i select the block and run the command `gc` or gbc it commenting out wrong

## Wrong Comment

`gc`
```
// <NotificationProvider>
//   <Component {...pageProps} />
// </NotificationProvider>
```
`gbc`
```
/* <NotificationProvider>
  <Component {...pageProps} />
</NotificationProvider> */
```

## Correct comment
```
{/* <NotificationProvider>
  <Component {...pageProps} />
</NotificationProvider> */}
```

![Screenshot 2024-01-24 at 6 16 19 PM](https://github.com/numToStr/Comment.nvim/assets/2174170/8e0c920b-8588-47af-966f-d18da87b5de2)

**Comment by RainYuGG** [comment]
There is the solution in [README](https://github.com/numToStr/Comment.nvim#-treesitter)

You should addtionally install [nvim-ts-context-commentstring ](https://github.com/JoosepAlviste/nvim-ts-context-commentstring#commentnvim) and use pre_hook in setup

```
require('Comment').setup({
    pre_hook = require('ts_context_commentstring.integrations.comment_nvim').create_pre_hook(),
})
```

**Comment by quolpr** [comment]
@khanakia did it helped you? I am still have same issue with commenting even after adding this:
```
require('Comment').setup({
    pre_hook = require('ts_context_commentstring.integrations.comment_nvim').create_pre_hook(),
})
```

On tsx file
