### ISSUE TITLE
Toggler remap with <leader>/ not working

### ISSUE THREAD

**Issue by slatifi** [numToStr/Comment.nvim#445]
I tried to remap the toggler bind from gcc to <leader>/ however it doesn't seem to update with leader configurations. Below is my lazy vim config:

```
{
        "numToStr/Comment.nvim",
        lazy = false,
        opts = {
            toggler = {
                line = "<leader>/",
            }
        },
        config = function()
            require("Comment").setup()
        end
    }
```

**Comment by matthewblott** [comment]
@slatifi try the following:

```lua
local comment = require('Comment')

comment.setup({
  toggler = {
    line = '<leader>/',
  },
})
```

**Comment by slatifi** [comment]
After some experimenting, removing all calls to the Setup() fn fixed the issue, i.e. removing the config block from above. 

LazyVim makes this call implicitly so by calling it manually, you are overwriting the configs.
