### ISSUE TITLE
How to recreate vscode-like behavior?

### ISSUE THREAD

**Issue by sfc-gh-plis** [numToStr/Comment.nvim#474]
I just want it to comment/uncomment lines in both normal and visual mode with a single shortcut and with the same speed. 
So far my config looks like this: 
```
   {
    'numToStr/Comment.nvim',
    opts = { ignore = '^$', toggler = { line = 'gc' }, opleader = { line = 'gl' }, mappings = { extra = false } },
  },
```
which is fast in visual mode, but slow in normal mode, as it waits for the potential follow up to the command (e.g. `gcw`). How to achieve the desired behavior, assuming I don't want anything other than line-wise comment/uncomment.

**Comment by omeyenburg** [comment]
You can create your own key mapping using the `Comment.api`. To avoid any delays, you can use vim.keymap.del to remove the default `gcc` mapping.

Interestingly, during my testing, I found that it wasn't necessary to remove operator-pending mappings like `gcw` and similar ones. If this isn't the case for you, you might want to set `extra = false` in the `opts` again.

Here is a minimal lazy.nvim example:
```lua
{
    'numToStr/Comment.nvim',
    config = function()
        vim.keymap.del('n', 'gcc')
        vim.keymap.set('n', 'gc', require('Comment.api').toggle.linewise.current)
    end,
},
```

It is not the most elegant solution and I'm sure there is a way to achieve such behaviour through the `opts`.
But I hope it helps!

**Comment by sfc-gh-plis** [comment]
That's good enough. Thanks!

**Comment by sfc-gh-plis** [comment]
One more difference I noticed, is that after running `gc` on the visual block, the visual selection is removed - which is consistent with other vim commands, but what if I wanted to keep the selection? So that `gc`, `gc` would comment and then uncomment the same selection.

**Comment by omeyenburg** [comment]
You can reselect your previous selection using `gv`. If you want, you can also do it automatically when pressing `gc`:
```Lua
vim.keymap.set('n', 'gc', function()
    require('Comment.api').toggle.linewise.current()
    vim.cmd('normal! gv')
end)
```

**Comment by sfc-gh-plis** [comment]
I see. I'm not sure it works though. 

This is the result of running `gc gc` on a visual selection. 
![image](https://github.com/numToStr/Comment.nvim/assets/141331616/a5597b5d-8642-48e8-bf0e-cc1e6a427f1e)

This is the result of running `gc` on a single line in normal mode, note that those 3 selected lines correspond to a visual block from a previous unrelated command. 
![image](https://github.com/numToStr/Comment.nvim/assets/141331616/b55923b3-7c1f-41b8-b4dd-2906301a23e7)

**Comment by sfc-gh-plis** [comment]
This is what worked for me, eventually :)
```lua
  {
    'numToStr/Comment.nvim',
    config = function()
      -- To avoid waiting for g@
      vim.keymap.del('n', 'gcc')

      -- Unify shortcut for normal and visual modes
      vim.keymap.set('n', 'gc', function()
        require('Comment.api').toggle.linewise.current()
      end)

      -- Preserve visual selection after toggling comment/uncomment
      vim.keymap.set('x', 'gc', function()
        local api = require 'Comment.api'
        local esc = vim.api.nvim_replace_termcodes('<ESC>', true, false, true)
        vim.api.nvim_feedkeys(esc, 'nx', false)
        api.locked 'toggle.linewise'(vim.fn.visualmode())
        vim.cmd 'normal! gv'
      end, { desc = 'Comment toggle linewise (visual) and preserve the visual selection' })
    end,
  },
```

**Comment by omeyenburg** [comment]
Nice to see! I guess I should have tested my solution..

**Comment by sfc-gh-plis** [comment]
Thanks for all your help, though! It was very helpful as those are literally my first few lines of code written in lua. It's fun!
