### ISSUE TITLE
Nix: line comment command uses /*%s*/ instead of #%s

### ISSUE THREAD

**Issue by ymarkus** [numToStr/Comment.nvim#63]
If I try to add a line comment in a nix file by using `gcc`, the line will be changed like this:
```nix
/*{ plugin = headwind-nvim; config = "lua require'headwind'.setup{}"; }*/
```
instead of this:
```nix
#{ plugin = headwind-nvim; config = "lua require'headwind'.setup{}"; }
```

If I add this to my config:
```lua
local ft = require('Comment.ft')
ft.nix = {'#%s', '/*%s*/'}
```
it now works properly.

**Comment by numToStr** [comment]
What's the `filetype` of your file? The `nix` commentstring is correct and is the same as you mentioned.

**Comment by ymarkus** [comment]
You're right, sorry. Seems to have been an issue on my end. I tried some stuff and now it works out of the box, thanks anyway!
