### ISSUE TITLE
Does not work with aligned C++ multiblock comment frame

### ISSUE THREAD

**Issue by krishnakumarg1984** [numToStr/Comment.nvim#68]
In C++, when one already has aligned comment-frame (e.g. notes for me inserted by a colleague using an external tool like [`par`](http://www.nicemice.net/par/) or [`boxes`](https://boxes.thomasjensen.com/examples.html) or with another neovim plugin, e.g. [`nvim-commentframe`](https://github.com/s1n7ax/nvim-comment-frame)), the keystroke **`gb}`** at the start of the multi-line comment does not correctly uncomment the multi-line commented block.

## Example 
``` c++
int main() {

    /*
     * Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy
     * eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam
     * voluptua.At vero eos et accusam et justo duo dolores et ea rebum.Stet
     * clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit
     * amet.
     */

    return 0;
}
```

### Expected output of `gb}` at the start of the comment block
```
     Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy
     eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam
     voluptua.At vero eos et accusam et justo duo dolores et ea rebum.Stet
     clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit
     amet.

```
### Current output of `gb}` at the start of the comment block
```
     * Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy
     * eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam
     * voluptua.At vero eos et accusam et justo duo dolores et ea rebum.Stet
     * clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit
     * amet.
```

**Comment by numToStr** [comment]
For c++, the block comment is just `/* */` so the plugin only knows about those characters. So this is expected.
