### ISSUE TITLE
Last visual selection is broken

### ISSUE THREAD

**Issue by jandamm** [numToStr/Comment.nvim#76]
1. Press `ggV5j`
2. Press `gc`
3. Press `gv`

Behavior:
First line of the file is selected

Expectation:
First five lines of the file are selected.

**Comment by numToStr** [comment]
Are you sure this is related to this plugin?

**Comment by jandamm** [comment]
Well it does work when replacing step 2 with `<ESC>`, `>`.
It's also working with `vim-sandwich`es `S` (when used with surround mode).

So the only time I've got this issue it's with `gc` from this plugin.

**Comment by numToStr** [comment]
Hmm. I have no idea what's causing this. Would you mind testing this behavior with `tcomment` and `vim-commentary`?

**Comment by jandamm** [comment]
Haven't used tcomment before.
It has been working with commentary until I switched about a month ago.

Does your code visually select a range? This would explain this issue.
I've also read that some nvim api calls mess with marks. The last visual selection isn't more than two marks (`<` and `>`). Maybe that's the issue?

**Comment by numToStr** [comment]
Ok, I get it now. This might be another version of #24 because marks disappear after commenting.

**Comment by jandamm** [comment]
Maybe it would be possible to store the selection, comment, select the stored selection and then exit visual mode.
This would at least fix `gv`.

**Comment by numToStr** [comment]
> Maybe it would be possible to store the selection, comment, select the stored selection and then exit visual mode.

That feels like a hack and I also think this would create a flash for a split second. I would rather prefer to fix #24.

**Comment by jandamm** [comment]
@numToStr I've migrated the opfunc used for visual `gc` to `nvim_buf_set_text` but it didn't help with `gv`.

Replacing this line
https://github.com/numToStr/Comment.nvim/blob/620445b87a0d1640fac6991f9c3338af8dec1884/lua/Comment/opfunc.lua#L166
with
```lua
    local ecol = p.ecol or #vim.api.nvim_buf_get_lines(0, p.erow - 1, p.erow, false)[1]
    A.nvim_buf_set_text(0, p.srow - 1, 0, p.erow - 1, ecol, p.lines)
```

**Comment by numToStr** [comment]
> @numToStr I've migrated the opfunc used for visual `gc` to `nvim_buf_set_text` but it didn't help with `gv`.

Yes, `nvim_buf_set_text` doesn't preserve marks. But `lockmarks` seems to fix the issue (I  have only tested it briefly)

**Comment by jandamm** [comment]
```
    local ecol = p.ecol or #vim.api.nvim_buf_get_lines(0, p.erow - 1, p.erow, false)[1]
    vim.cmd('lockmarks lua vim.api.nvim_buf_set_text(0, ' .. p.srow .. '- 1, 0, ' .. p.erow .. ' - 1, ' .. ecol .. ', ' .. vim.inspect(p.lines) .. ')')
```
This would work 👍

**Comment by numToStr** [comment]
`lockmarks` also works with `nvim_buf_set_lines` :)

(I'll try to fix this soon enough)

**Comment by numToStr** [comment]
@jandamm Care to test #110?

**Comment by jandamm** [comment]
Looks good to me 👍
