### ISSUE TITLE
Toggle comment on word doesn't work

### ISSUE THREAD

**Issue by darkangel-ua** [numToStr/Comment.nvim#77]
I think it worked before but now any time I do `gciw` it comments the word and next `gciw` will generate nested comment instead of removing previous one. Is it just my issue? I'm trying that on `lua` and `cpp` files with the same results.

**Comment by numToStr** [comment]
This is an expected behaviour. You might wanna read this https://www.reddit.com/r/neovim/comments/q35328/commentnvim_simple_and_powerful_comment_plugin/hfra1vo/. I've already explained this and there is nothing I can do about it right now.

**Comment by darkangel-ua** [comment]
Oh, I see... Thanks for explanation. I've figured out that the behavior I wanted to achieve easily can be done by `gciC` where `iC` mapped to `@comment.outer` `treesitter` text object.

**Comment by numToStr** [comment]
> I've figured out that the behavior I wanted to achieve easily can be done by gciC where iC mapped to @comment.outer treesitter text object.

Ok, that's freakin cool. I never thought of that. Thanks for the tip 😄
