### ISSUE TITLE
Add an option for enforcing `gc` for line comments only and `gb` for block comments only

### ISSUE THREAD

**Issue by snezhniylis** [numToStr/Comment.nvim#79]
### Current behaviour

Performing `gc` on a text object that is within a single line's bounds puts it in a block comment.

### Expected behaviour

Performing `gc` will always comment selected range line-wise. For block comments, I can always use `gb`. [kommentary](https://github.com/b3nj5m1n/kommentary) has `prefer_single_line_comments` option, which does exactly that.

### Some examples

-  `gcl`
   ```lua
   ▏ return function() end
   ```
   Result:
   ```lua
    --[[   ]]return function() end
   ```
   Expected:
   ```lua
     -- return function() end
   ```

- `gcaf` (w/ tree-sitter)
   ```lua
   ▏
     return function() end
   ```
   Result:
   ```lua
    
     return --[[ function() end ]]
   ```
   Expected:
   ```lua
    
     -- return function() end
   ```

## Proposed solution

Modify [`block_x` definition](https://github.com/numToStr/Comment.nvim/blob/a6e1c127fa7f19ec4e3edbffab1aacb2852b6db3/lua/Comment/opfunc.lua#L54) to include the option for enforcing comment type.

```lua
    local block_x = partial_block and same_line and not (cfg.enforced_type and ctype == U.ctype.line)
```

**Comment by numToStr** [comment]
The behavior you want is already achievable with `gcc`.

And IMO, the current behavior is expected and should be the default. And I don't want to add some niche options to the plugin :)

**Comment by snezhniylis** [comment]
Fair enough. I proposed this, because of the following issue. If it's not convincing, you can freely close this issue.

#### Increased mental load because of inconsistency

- Commenting objects with `gca{`/`gcia`(ts)/`gcaf`(ts)/... results in a block comment if the object is on single line, yet, for multi-line, it's line-wise. 
  - Same can be said about motions, e.g. `gcl` vs `gcj`.
- **`gc` - line comment, `gb` - block comment** is easy to remember subconsciously, **`gc` - line/block comment, `gb` - block comment** is not.

I constantly find myself doing comment undos, because I mindlessly comment without thinking whether the object is multi-line or single-line. Considering my tree-sitter text object workflow, this is very annoying. Getting used to block comments for certain object types, yet sometimes they don't work. Or vice versa. This "unpredictability" and having to stop to think about what keybind I should press partially defeats the purpose of vim-workflow.

---

My proposal removes this mental load completely. In a sense that it's always predictable `[action][motion/text_object]` with actions:
`gc` - apply comment to whole line
`gb` - apply comment to range

Working with this approach for the last 3 days has been much more pleasant.

**Comment by numToStr** [comment]
I did that because most user starts commenting with `gc` and pressing `gc{left/right motion}`  like `gcw` `gc$` should use block comments even if `gc` means line comments. I am also getting where you are coming from, it's just no one complained about this behavior before.

Still, I need to balance the sane defaults and customizability of the plugin :)
