### ISSUE TITLE
Option to duplicate + comment

### ISSUE THREAD

**Issue by jeetsukumaran** [numToStr/Comment.nvim#84]
Very often I like to duplicate a block of code and comment out a copy. 

For example,

```python
for i in range(2, 20:
     print(i)
```
```python
# for i in range(2, 20:
#     print(i)
for i in range(2, 20:
     print(i)
```

Right now, I have to repeat a motion twice -- once to yank and once to comment out.  And then of course I have to hit ``p`` to paste in the duplicate. It gets more complicated if I have to avoid clobbering my default register. 

It would be nice to have this all rolled into one motion (that takes care of saving/restoring the registers).
Eg., ``gC" (or ``gy`` etc.) will behave just like ``gc`` but will paste a copy of the uncommented code next to the commented one.

Is it possible to support this?

**Comment by gegoune** [comment]
Duplicate #70.

**Comment by numToStr** [comment]
@jeetsukumaran This was already requested earlier. You should also follow https://github.com/numToStr/Comment.nvim/pull/73 where I gave an example of how to achieve this :)

**Comment by jeetsukumaran** [comment]
Thanks! Will do. And thanks for this plugin :)
