### ISSUE TITLE
Allow extra mappings to be configured

### ISSUE THREAD

**Issue by nwithers-ecr** [numToStr/Comment.nvim#85]
I prefer to use the `<Leader>` key, rather than g, which is easy enough for the basic configs. 
```lua
require('Comment').setup {
    toggler = {
        line = '<Leader>cc',
        block = '<Leader>bv',
    },
    opleader = {
        line = '<Leader>c',
        block = '<Leader>b',
    },
}
``` 
I would like to type `<Leader>co` instead of `gco` but it seems they are hard-coded with no way to change them with setup{} https://github.com/numToStr/Comment.nvim/blob/master/lua/Comment/api.lua#L240

**Comment by numToStr** [comment]
@nwithers-ecr Thanks for pointing this out. I am also aware of this and I am also thinking of a way to elegantly configure all the mappings. Currently, I am thinking of doing this https://github.com/numToStr/Comment.nvim/pull/45#issuecomment-945148430 and later find a better way. If you have any suggestions I would love to hear them :)

**Comment by nwithers-ecr** [comment]
That sounds good. The only feedback I have is perhaps using `above` and `below` rather than `up` and `down`

**Comment by numToStr** [comment]
> The only feedback I have is perhaps using `above` and `below` rather than `up` and `down`

That sounds reasonable. Thanks 👍.

**Comment by darzok0914** [comment]
I managed to have my custom mappings, I had a similar use case, I opened and closed this issue https://github.com/numToStr/Comment.nvim/issues/87 as I basically found out a way to achieve it

**Comment by nwithers-ecr** [comment]
There's probably a cleaner way but, I just edited the plugin source and replaced `g` with <Leader>
