### ISSUE TITLE
Issue with bindings + commands that enter insert mode

### ISSUE THREAD

**Issue by Grazfather** [numToStr/Comment.nvim#88]
If I bind something that includes a comment.nvim binding, e.g one that adds a comment:

`gcATEST` you'd expect that `TEST` would be added to the comment, but it seems that when `TEST` is input Vim is not yet in insert mode.

`gcAaTEST<ESC>` tries to account for this, but then I'm left in insert mode at the end.

`gcAaTEST` yields a comment string `TESTa`, hinting that you're using `a` to get into insert mode.

It seems that the command is not done synchronously and this makes is to there's a bit of a race between the function behind `gcA` and the rest of my mapping.

**Comment by numToStr** [comment]
I am aware of this issue. I am using `vim.api.nvim_feedkeys` which might be the cause of the issue. It's just I don't know how to fix this or if this is even fixable.

**Comment by Grazfather** [comment]
Interesting. The docs say that it should be blocking and that `nvim_input` is async.

I can repro the issue with this binding: `"<cmd>lua vim.api.nvim_feedkeys('jjja', 'n', true)<CR>jjj<ESC>"` which should append `jjj` to three lines down, but instead it goes six lines down.

This doesn't seem correct neovim behaviour.

**Comment by numToStr** [comment]
This could be a bug indeed. Maybe you can report this behavior to neovim.

**Comment by Grazfather** [comment]
Filed neovim/neovim#16571 to see whether it's a neovim issue.

**Comment by numToStr** [comment]
@Grazfather Great, thanks! I am also looking forward to the explanation.

**Comment by Grazfather** [comment]
Looks like it's expected behaviour, but you can fix by changing the mode from "n" to "ni".
https://github.com/neovim/neovim/issues/16571#issuecomment-988890572

**Comment by numToStr** [comment]
Care to test and make a PR ;)

**Comment by Grazfather** [comment]
Done
