### ISSUE TITLE
Problem with commenting /etc/pacman.conf

### ISSUE THREAD

**Issue by roland-rollo** [numToStr/Comment.nvim#90]
Hi,

I have little strange problem. I use Arch Linux, and there is `/etc/pacman.conf` where you configure option for Arch package manager.
If I do this with
```
sudo nvim /etc/pacman.conf
```
or as root
```
nvim /etc/pacman.conf
```
And I do `gcc` it add at start of line `; `, like from
```
#NoUpgrade   =
```
to
```
; #NoUpgrade   =
```
But if I do this with command
```
sudoedit /etc/pacman.conf
```
It commenting and uncommenting without problem.
I even nuked my `init.lua` config to just
```lua
-- load plugin manager first
require('plugins._packer')
```
To be sure, that nothing from my neovim config interrupt with Comment.nvim, but without success.

**Comment by numToStr** [comment]
By default `pacman.conf` is detected as `dosini` filetype and commentstring is set to `;`. So you need to change the filetype to `conf` then you won't face any issues.

**Comment by numToStr** [comment]
Add the following to your neovim config
```vim
aucmd BufNewFile,BufRead *.conf set ft=conf
```

**Comment by numToStr** [comment]
I am going to close as this is not related to this plugin :)

**Comment by roland-rollo** [comment]
> Add the following to your neovim config
> 
> ```viml
> aucmd BufNewFile,BufRead *.conf set ft=conf
> ```

I very appreciate for your fast answer. It didn't work, but I changed it to
```lua
vim.cmd([[
    autocmd BufNewFile,BufRead *.conf set ft=conf
]])
```
And it worked flawlessly. Very much love. <3 Thank you!
