### ISSUE TITLE
Add [count]gbc keymap

### ISSUE THREAD

**Issue by kuznetsss** [numToStr/Comment.nvim#95]
Hi! Thank you for the plugin, it's really useful!

I'm really missing the feature to toggle block comment for multiple lines using `[count]gbc` keymap. What do you think about adding it?

I know that there is `gb[count]{motion}` but for me it's less comfortable

**Comment by numToStr** [comment]
I am already planning to add this after I merge this #94 :)

**Comment by numToStr** [comment]
Wanna try #97
