### ISSUE TITLE
Expose `<Plug>` mappings

### ISSUE THREAD

**Issue by numToStr** [numToStr/Comment.nvim#96]
> I can't do much about it. You'll still need to know a little about how VISUAL mode works. Also, we can mention this in docs :)

My mappings with Kommentay were like this:

```lua
local map = require'map'
map.n{'<leader>c', '<Plug>kommentary_line_default', noremap = false}
map.x{'<leader>c', '<Plug>kommentary_visual_default<C-c>', noremap = false}
```
I don't know what it's going on under the hood. I wonder if it's something that could be applied here as well?

_Originally posted by @mbenford in https://github.com/numToStr/Comment.nvim/issues/78#issuecomment-992833436_

**Comment by jrafaaael** [comment]
hello. Any advance?

**Comment by numToStr** [comment]
@jrafaaael See the attached PR :)
